namespace PomoMeetApp.View
{
    partial class Dashboard
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            siticoneLabel1 = new SiticoneNetCoreUI.SiticoneLabel();
            siticoneLabel2 = new SiticoneNetCoreUI.SiticoneLabel();
            mySiticoneLicenseSettings1 = new SiticoneNetCoreUI.MySiticoneLicenseSettings();
            sbtn_CreateNewRoom = new SiticoneNetCoreUI.SiticoneButton();
            mySiticoneLicenseSettings2 = new SiticoneNetCoreUI.MySiticoneLicenseSettings();
            siticoneButton7 = new SiticoneNetCoreUI.SiticoneButton();
            siticoneTextBox1 = new SiticoneNetCoreUI.SiticoneTextBox();
            siticoneButton8 = new SiticoneNetCoreUI.SiticoneButton();
            siticoneButton9 = new SiticoneNetCoreUI.SiticoneButton();
            siticoneButton10 = new SiticoneNetCoreUI.SiticoneButton();
            siticoneButton11 = new SiticoneNetCoreUI.SiticoneButton();
            siticoneButton12 = new SiticoneNetCoreUI.SiticoneButton();
            siticoneButton13 = new SiticoneNetCoreUI.SiticoneButton();
            mySiticoneLicenseSettings3 = new SiticoneNetCoreUI.MySiticoneLicenseSettings();
            sideBar1 = new SideBar();
            userProfilePanel2 = new UserProfilePanel();
            SuspendLayout();
            // 
            // siticoneLabel1
            // 
            siticoneLabel1.BackColor = Color.Transparent;
            siticoneLabel1.Font = new Font("Inter", 24F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneLabel1.Location = new Point(322, 23);
            siticoneLabel1.Name = "siticoneLabel1";
            siticoneLabel1.Size = new Size(125, 65);
            siticoneLabel1.TabIndex = 6;
            siticoneLabel1.Text = "Hi, ";
            // 
            // siticoneLabel2
            // 
            siticoneLabel2.BackColor = Color.Transparent;
            siticoneLabel2.Font = new Font("Inter", 24F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneLabel2.Location = new Point(322, 88);
            siticoneLabel2.Name = "siticoneLabel2";
            siticoneLabel2.Size = new Size(708, 65);
            siticoneLabel2.TabIndex = 7;
            siticoneLabel2.Text = "Chào mừng bạn đến với PomoMeet";
            // 
            // sbtn_CreateNewRoom
            // 
            sbtn_CreateNewRoom.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            sbtn_CreateNewRoom.AccessibleName = "Create a new room";
            sbtn_CreateNewRoom.AutoSizeBasedOnText = false;
            sbtn_CreateNewRoom.BackColor = Color.Transparent;
            sbtn_CreateNewRoom.BadgeBackColor = Color.Red;
            sbtn_CreateNewRoom.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            sbtn_CreateNewRoom.BadgeValue = 0;
            sbtn_CreateNewRoom.BadgeValueForeColor = Color.White;
            sbtn_CreateNewRoom.BorderColor = Color.Transparent;
            sbtn_CreateNewRoom.BorderWidth = 2;
            sbtn_CreateNewRoom.ButtonBackColor = Color.White;
            sbtn_CreateNewRoom.ButtonImage = Properties.Resources.create_Room1;
            sbtn_CreateNewRoom.CanBeep = true;
            sbtn_CreateNewRoom.CanGlow = false;
            sbtn_CreateNewRoom.CanShake = true;
            sbtn_CreateNewRoom.ContextMenuStripEx = null;
            sbtn_CreateNewRoom.CornerRadiusBottomLeft = 12;
            sbtn_CreateNewRoom.CornerRadiusBottomRight = 12;
            sbtn_CreateNewRoom.CornerRadiusTopLeft = 12;
            sbtn_CreateNewRoom.CornerRadiusTopRight = 12;
            sbtn_CreateNewRoom.CustomCursor = Cursors.Default;
            sbtn_CreateNewRoom.DisabledTextColor = Color.White;
            sbtn_CreateNewRoom.EnableLongPress = false;
            sbtn_CreateNewRoom.EnablePressAnimation = true;
            sbtn_CreateNewRoom.EnableRippleEffect = true;
            sbtn_CreateNewRoom.EnableShadow = false;
            sbtn_CreateNewRoom.EnableTextWrapping = false;
            sbtn_CreateNewRoom.Font = new Font("Inter ExtraBold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            sbtn_CreateNewRoom.GlowColor = Color.FromArgb(117, 164, 127);
            sbtn_CreateNewRoom.GlowIntensity = 100;
            sbtn_CreateNewRoom.GlowRadius = 20F;
            sbtn_CreateNewRoom.GradientBackground = true;
            sbtn_CreateNewRoom.GradientColor = Color.FromArgb(117, 164, 127);
            sbtn_CreateNewRoom.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            sbtn_CreateNewRoom.HintText = null;
            sbtn_CreateNewRoom.HoverBackColor = Color.FromArgb(117, 164, 127);
            sbtn_CreateNewRoom.HoverFontStyle = FontStyle.Regular;
            sbtn_CreateNewRoom.HoverTextColor = Color.White;
            sbtn_CreateNewRoom.HoverTransitionDuration = 250;
            sbtn_CreateNewRoom.ImageAlign = ContentAlignment.MiddleRight;
            sbtn_CreateNewRoom.ImagePadding = 5;
            sbtn_CreateNewRoom.ImageSize = new Size(50, 50);
            sbtn_CreateNewRoom.IsRadial = false;
            sbtn_CreateNewRoom.IsReadOnly = false;
            sbtn_CreateNewRoom.IsToggleButton = false;
            sbtn_CreateNewRoom.IsToggled = false;
            sbtn_CreateNewRoom.Location = new Point(325, 164);
            sbtn_CreateNewRoom.LongPressDurationMS = 1000;
            sbtn_CreateNewRoom.Name = "sbtn_CreateNewRoom";
            sbtn_CreateNewRoom.NormalFontStyle = FontStyle.Regular;
            sbtn_CreateNewRoom.Padding = new Padding(20, 0, 0, 0);
            sbtn_CreateNewRoom.ParticleColor = Color.FromArgb(200, 200, 200);
            sbtn_CreateNewRoom.ParticleCount = 15;
            sbtn_CreateNewRoom.PressAnimationScale = 0.97F;
            sbtn_CreateNewRoom.PressedBackColor = Color.FromArgb(74, 128, 235);
            sbtn_CreateNewRoom.PressedFontStyle = FontStyle.Regular;
            sbtn_CreateNewRoom.PressTransitionDuration = 150;
            sbtn_CreateNewRoom.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            sbtn_CreateNewRoom.RippleColor = Color.FromArgb(255, 255, 255);
            sbtn_CreateNewRoom.RippleOpacity = 0.3F;
            sbtn_CreateNewRoom.RippleRadiusMultiplier = 0.6F;
            sbtn_CreateNewRoom.ShadowBlur = 5;
            sbtn_CreateNewRoom.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            sbtn_CreateNewRoom.ShadowOffset = new Point(2, 2);
            sbtn_CreateNewRoom.ShakeDuration = 500;
            sbtn_CreateNewRoom.ShakeIntensity = 5;
            sbtn_CreateNewRoom.Size = new Size(342, 57);
            sbtn_CreateNewRoom.TabIndex = 8;
            sbtn_CreateNewRoom.Text = "Create a new room";
            sbtn_CreateNewRoom.TextAlign = ContentAlignment.MiddleCenter;
            sbtn_CreateNewRoom.TextColor = Color.White;
            sbtn_CreateNewRoom.TooltipText = null;
            sbtn_CreateNewRoom.UseAdvancedRendering = true;
            sbtn_CreateNewRoom.UseParticles = false;
            sbtn_CreateNewRoom.Click += sbtn_CreateNewRoom_Click;
            // 
            // siticoneButton7
            // 
            siticoneButton7.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButton7.AccessibleName = "Join a room";
            siticoneButton7.AutoSizeBasedOnText = false;
            siticoneButton7.BackColor = Color.Transparent;
            siticoneButton7.BadgeBackColor = Color.Red;
            siticoneButton7.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            siticoneButton7.BadgeValue = 0;
            siticoneButton7.BadgeValueForeColor = Color.White;
            siticoneButton7.BorderColor = Color.Transparent;
            siticoneButton7.BorderWidth = 2;
            siticoneButton7.ButtonBackColor = Color.White;
            siticoneButton7.ButtonImage = null;
            siticoneButton7.CanBeep = true;
            siticoneButton7.CanGlow = false;
            siticoneButton7.CanShake = true;
            siticoneButton7.ContextMenuStripEx = null;
            siticoneButton7.CornerRadiusBottomLeft = 12;
            siticoneButton7.CornerRadiusBottomRight = 12;
            siticoneButton7.CornerRadiusTopLeft = 12;
            siticoneButton7.CornerRadiusTopRight = 12;
            siticoneButton7.CustomCursor = Cursors.Default;
            siticoneButton7.DisabledTextColor = Color.White;
            siticoneButton7.EnableLongPress = false;
            siticoneButton7.EnablePressAnimation = true;
            siticoneButton7.EnableRippleEffect = true;
            siticoneButton7.EnableShadow = false;
            siticoneButton7.EnableTextWrapping = false;
            siticoneButton7.Font = new Font("Inter ExtraBold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneButton7.GlowColor = Color.FromArgb(117, 164, 127);
            siticoneButton7.GlowIntensity = 100;
            siticoneButton7.GlowRadius = 20F;
            siticoneButton7.GradientBackground = true;
            siticoneButton7.GradientColor = Color.FromArgb(117, 164, 127);
            siticoneButton7.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButton7.HintText = null;
            siticoneButton7.HoverBackColor = Color.FromArgb(117, 164, 127);
            siticoneButton7.HoverFontStyle = FontStyle.Regular;
            siticoneButton7.HoverTextColor = Color.White;
            siticoneButton7.HoverTransitionDuration = 250;
            siticoneButton7.ImageAlign = ContentAlignment.MiddleRight;
            siticoneButton7.ImagePadding = 5;
            siticoneButton7.ImageSize = new Size(50, 50);
            siticoneButton7.IsRadial = false;
            siticoneButton7.IsReadOnly = false;
            siticoneButton7.IsToggleButton = false;
            siticoneButton7.IsToggled = false;
            siticoneButton7.Location = new Point(688, 164);
            siticoneButton7.LongPressDurationMS = 1000;
            siticoneButton7.Name = "siticoneButton7";
            siticoneButton7.NormalFontStyle = FontStyle.Regular;
            siticoneButton7.Padding = new Padding(20, 0, 0, 0);
            siticoneButton7.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButton7.ParticleCount = 15;
            siticoneButton7.PressAnimationScale = 0.97F;
            siticoneButton7.PressedBackColor = Color.FromArgb(74, 128, 235);
            siticoneButton7.PressedFontStyle = FontStyle.Regular;
            siticoneButton7.PressTransitionDuration = 150;
            siticoneButton7.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButton7.RippleColor = Color.FromArgb(255, 255, 255);
            siticoneButton7.RippleOpacity = 0.3F;
            siticoneButton7.RippleRadiusMultiplier = 0.6F;
            siticoneButton7.ShadowBlur = 5;
            siticoneButton7.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            siticoneButton7.ShadowOffset = new Point(2, 2);
            siticoneButton7.ShakeDuration = 500;
            siticoneButton7.ShakeIntensity = 5;
            siticoneButton7.Size = new Size(180, 57);
            siticoneButton7.TabIndex = 9;
            siticoneButton7.Text = "Join a room";
            siticoneButton7.TextAlign = ContentAlignment.MiddleCenter;
            siticoneButton7.TextColor = Color.White;
            siticoneButton7.TooltipText = null;
            siticoneButton7.UseAdvancedRendering = true;
            siticoneButton7.UseParticles = false;
            // 
            // siticoneTextBox1
            // 
            siticoneTextBox1.AccessibleDescription = "A customizable text input field.";
            siticoneTextBox1.AccessibleName = "Text Box";
            siticoneTextBox1.AccessibleRole = AccessibleRole.Text;
            siticoneTextBox1.BackColor = Color.Transparent;
            siticoneTextBox1.BlinkCount = 3;
            siticoneTextBox1.BlinkShadow = false;
            siticoneTextBox1.BorderColor1 = Color.LightSlateGray;
            siticoneTextBox1.BorderColor2 = Color.LightSlateGray;
            siticoneTextBox1.BorderFocusColor1 = Color.FromArgb(77, 77, 255);
            siticoneTextBox1.BorderFocusColor2 = Color.FromArgb(77, 77, 255);
            siticoneTextBox1.CanShake = true;
            siticoneTextBox1.ContinuousBlink = false;
            siticoneTextBox1.CornerRadiusBottomLeft = 10;
            siticoneTextBox1.CornerRadiusBottomRight = 10;
            siticoneTextBox1.CornerRadiusTopLeft = 10;
            siticoneTextBox1.CornerRadiusTopRight = 10;
            siticoneTextBox1.CursorBlinkRate = 500;
            siticoneTextBox1.CursorColor = Color.Black;
            siticoneTextBox1.CursorHeight = 26;
            siticoneTextBox1.CursorOffset = 0;
            siticoneTextBox1.CursorStyle = SiticoneNetCoreUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            siticoneTextBox1.CursorWidth = 1;
            siticoneTextBox1.DisabledBackColor = Color.WhiteSmoke;
            siticoneTextBox1.DisabledBorderColor = Color.LightGray;
            siticoneTextBox1.DisabledTextColor = Color.Gray;
            siticoneTextBox1.EnableDropShadow = false;
            siticoneTextBox1.FillColor1 = Color.YellowGreen;
            siticoneTextBox1.FillColor2 = Color.White;
            siticoneTextBox1.Font = new Font("Segoe UI", 9.5F);
            siticoneTextBox1.ForeColor = Color.DimGray;
            siticoneTextBox1.HoverBorderColor1 = Color.Gray;
            siticoneTextBox1.HoverBorderColor2 = Color.Gray;
            siticoneTextBox1.IsEnabled = true;
            siticoneTextBox1.Location = new Point(1068, 171);
            siticoneTextBox1.Name = "siticoneTextBox1";
            siticoneTextBox1.PlaceholderColor = Color.Gray;
            siticoneTextBox1.PlaceholderText = "Enter text here...";
            siticoneTextBox1.ReadOnlyBorderColor1 = Color.LightGray;
            siticoneTextBox1.ReadOnlyBorderColor2 = Color.LightGray;
            siticoneTextBox1.ReadOnlyFillColor1 = Color.WhiteSmoke;
            siticoneTextBox1.ReadOnlyFillColor2 = Color.WhiteSmoke;
            siticoneTextBox1.ReadOnlyPlaceholderColor = Color.DarkGray;
            siticoneTextBox1.SelectionBackColor = Color.FromArgb(77, 77, 255);
            siticoneTextBox1.ShadowAnimationDuration = 1;
            siticoneTextBox1.ShadowBlur = 10;
            siticoneTextBox1.ShadowColor = Color.FromArgb(15, 0, 0, 0);
            siticoneTextBox1.Size = new Size(294, 50);
            siticoneTextBox1.SolidBorderColor = Color.LightSlateGray;
            siticoneTextBox1.SolidBorderFocusColor = Color.FromArgb(77, 77, 255);
            siticoneTextBox1.SolidBorderHoverColor = Color.Gray;
            siticoneTextBox1.SolidFillColor = Color.White;
            siticoneTextBox1.TabIndex = 11;
            siticoneTextBox1.Text = "Search here ...";
            siticoneTextBox1.TextPadding = new Padding(16, 0, 6, 0);
            siticoneTextBox1.ValidationErrorMessage = "Invalid input.";
            siticoneTextBox1.ValidationFunction = null;
            // 
            // siticoneButton8
            // 
            siticoneButton8.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButton8.AccessibleName = "Tham gia";
            siticoneButton8.AutoSizeBasedOnText = false;
            siticoneButton8.BackColor = Color.Transparent;
            siticoneButton8.BadgeBackColor = Color.Red;
            siticoneButton8.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            siticoneButton8.BadgeValue = 0;
            siticoneButton8.BadgeValueForeColor = Color.White;
            siticoneButton8.BorderColor = Color.Transparent;
            siticoneButton8.BorderWidth = 2;
            siticoneButton8.ButtonBackColor = Color.FromArgb(117, 164, 127);
            siticoneButton8.ButtonImage = Properties.Resources.background;
            siticoneButton8.CanBeep = true;
            siticoneButton8.CanGlow = false;
            siticoneButton8.CanShake = true;
            siticoneButton8.ContextMenuStripEx = null;
            siticoneButton8.CornerRadiusBottomLeft = 20;
            siticoneButton8.CornerRadiusBottomRight = 20;
            siticoneButton8.CornerRadiusTopLeft = 20;
            siticoneButton8.CornerRadiusTopRight = 20;
            siticoneButton8.CustomCursor = Cursors.Default;
            siticoneButton8.DisabledTextColor = Color.FromArgb(150, 150, 150);
            siticoneButton8.EnableLongPress = false;
            siticoneButton8.EnablePressAnimation = true;
            siticoneButton8.EnableRippleEffect = true;
            siticoneButton8.EnableShadow = false;
            siticoneButton8.EnableTextWrapping = false;
            siticoneButton8.Font = new Font("Inter SemiBold", 10.8F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneButton8.GlowColor = Color.FromArgb(100, 255, 255, 255);
            siticoneButton8.GlowIntensity = 100;
            siticoneButton8.GlowRadius = 20F;
            siticoneButton8.GradientBackground = false;
            siticoneButton8.GradientColor = Color.FromArgb(114, 168, 255);
            siticoneButton8.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButton8.HintText = null;
            siticoneButton8.HoverBackColor = Color.FromArgb(114, 168, 255);
            siticoneButton8.HoverFontStyle = FontStyle.Regular;
            siticoneButton8.HoverTextColor = Color.White;
            siticoneButton8.HoverTransitionDuration = 250;
            siticoneButton8.ImageAlign = ContentAlignment.MiddleLeft;
            siticoneButton8.ImagePadding = 5;
            siticoneButton8.ImageSize = new Size(300, 220);
            siticoneButton8.IsRadial = false;
            siticoneButton8.IsReadOnly = false;
            siticoneButton8.IsToggleButton = false;
            siticoneButton8.IsToggled = false;
            siticoneButton8.Location = new Point(308, 263);
            siticoneButton8.LongPressDurationMS = 1000;
            siticoneButton8.Name = "siticoneButton8";
            siticoneButton8.NormalFontStyle = FontStyle.Regular;
            siticoneButton8.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButton8.ParticleCount = 15;
            siticoneButton8.PressAnimationScale = 0.97F;
            siticoneButton8.PressedBackColor = Color.FromArgb(74, 128, 235);
            siticoneButton8.PressedFontStyle = FontStyle.Regular;
            siticoneButton8.PressTransitionDuration = 150;
            siticoneButton8.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButton8.RippleColor = Color.FromArgb(255, 255, 255);
            siticoneButton8.RippleOpacity = 0.3F;
            siticoneButton8.RippleRadiusMultiplier = 0.6F;
            siticoneButton8.ShadowBlur = 5;
            siticoneButton8.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            siticoneButton8.ShadowOffset = new Point(2, 2);
            siticoneButton8.ShakeDuration = 500;
            siticoneButton8.ShakeIntensity = 5;
            siticoneButton8.Size = new Size(310, 230);
            siticoneButton8.TabIndex = 12;
            siticoneButton8.Text = "Tham gia";
            siticoneButton8.TextAlign = ContentAlignment.MiddleCenter;
            siticoneButton8.TextColor = Color.Black;
            siticoneButton8.TooltipText = null;
            siticoneButton8.UseAdvancedRendering = true;
            siticoneButton8.UseParticles = false;
            // 
            // siticoneButton9
            // 
            siticoneButton9.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButton9.AccessibleName = "Tham gia";
            siticoneButton9.AutoSizeBasedOnText = false;
            siticoneButton9.BackColor = Color.Transparent;
            siticoneButton9.BadgeBackColor = Color.Red;
            siticoneButton9.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            siticoneButton9.BadgeValue = 0;
            siticoneButton9.BadgeValueForeColor = Color.White;
            siticoneButton9.BorderColor = Color.Transparent;
            siticoneButton9.BorderWidth = 2;
            siticoneButton9.ButtonBackColor = Color.FromArgb(117, 164, 127);
            siticoneButton9.ButtonImage = Properties.Resources.background;
            siticoneButton9.CanBeep = true;
            siticoneButton9.CanGlow = false;
            siticoneButton9.CanShake = true;
            siticoneButton9.ContextMenuStripEx = null;
            siticoneButton9.CornerRadiusBottomLeft = 20;
            siticoneButton9.CornerRadiusBottomRight = 20;
            siticoneButton9.CornerRadiusTopLeft = 20;
            siticoneButton9.CornerRadiusTopRight = 20;
            siticoneButton9.CustomCursor = Cursors.Default;
            siticoneButton9.DisabledTextColor = Color.FromArgb(150, 150, 150);
            siticoneButton9.EnableLongPress = false;
            siticoneButton9.EnablePressAnimation = true;
            siticoneButton9.EnableRippleEffect = true;
            siticoneButton9.EnableShadow = false;
            siticoneButton9.EnableTextWrapping = false;
            siticoneButton9.Font = new Font("Inter SemiBold", 10.8F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneButton9.GlowColor = Color.FromArgb(100, 255, 255, 255);
            siticoneButton9.GlowIntensity = 100;
            siticoneButton9.GlowRadius = 20F;
            siticoneButton9.GradientBackground = false;
            siticoneButton9.GradientColor = Color.FromArgb(114, 168, 255);
            siticoneButton9.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButton9.HintText = null;
            siticoneButton9.HoverBackColor = Color.FromArgb(114, 168, 255);
            siticoneButton9.HoverFontStyle = FontStyle.Regular;
            siticoneButton9.HoverTextColor = Color.White;
            siticoneButton9.HoverTransitionDuration = 250;
            siticoneButton9.ImageAlign = ContentAlignment.MiddleLeft;
            siticoneButton9.ImagePadding = 5;
            siticoneButton9.ImageSize = new Size(300, 220);
            siticoneButton9.IsRadial = false;
            siticoneButton9.IsReadOnly = false;
            siticoneButton9.IsToggleButton = false;
            siticoneButton9.IsToggled = false;
            siticoneButton9.Location = new Point(677, 263);
            siticoneButton9.LongPressDurationMS = 1000;
            siticoneButton9.Name = "siticoneButton9";
            siticoneButton9.NormalFontStyle = FontStyle.Regular;
            siticoneButton9.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButton9.ParticleCount = 15;
            siticoneButton9.PressAnimationScale = 0.97F;
            siticoneButton9.PressedBackColor = Color.FromArgb(74, 128, 235);
            siticoneButton9.PressedFontStyle = FontStyle.Regular;
            siticoneButton9.PressTransitionDuration = 150;
            siticoneButton9.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButton9.RippleColor = Color.FromArgb(255, 255, 255);
            siticoneButton9.RippleOpacity = 0.3F;
            siticoneButton9.RippleRadiusMultiplier = 0.6F;
            siticoneButton9.ShadowBlur = 5;
            siticoneButton9.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            siticoneButton9.ShadowOffset = new Point(2, 2);
            siticoneButton9.ShakeDuration = 500;
            siticoneButton9.ShakeIntensity = 5;
            siticoneButton9.Size = new Size(310, 230);
            siticoneButton9.TabIndex = 13;
            siticoneButton9.Text = "Tham gia";
            siticoneButton9.TextAlign = ContentAlignment.MiddleCenter;
            siticoneButton9.TextColor = Color.Black;
            siticoneButton9.TooltipText = null;
            siticoneButton9.UseAdvancedRendering = true;
            siticoneButton9.UseParticles = false;
            // 
            // siticoneButton10
            // 
            siticoneButton10.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButton10.AccessibleName = "Tham gia";
            siticoneButton10.AutoSizeBasedOnText = false;
            siticoneButton10.BackColor = Color.Transparent;
            siticoneButton10.BadgeBackColor = Color.Red;
            siticoneButton10.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            siticoneButton10.BadgeValue = 0;
            siticoneButton10.BadgeValueForeColor = Color.White;
            siticoneButton10.BorderColor = Color.Transparent;
            siticoneButton10.BorderWidth = 2;
            siticoneButton10.ButtonBackColor = Color.FromArgb(117, 164, 127);
            siticoneButton10.ButtonImage = Properties.Resources.background;
            siticoneButton10.CanBeep = true;
            siticoneButton10.CanGlow = false;
            siticoneButton10.CanShake = true;
            siticoneButton10.ContextMenuStripEx = null;
            siticoneButton10.CornerRadiusBottomLeft = 20;
            siticoneButton10.CornerRadiusBottomRight = 20;
            siticoneButton10.CornerRadiusTopLeft = 20;
            siticoneButton10.CornerRadiusTopRight = 20;
            siticoneButton10.CustomCursor = Cursors.Default;
            siticoneButton10.DisabledTextColor = Color.FromArgb(150, 150, 150);
            siticoneButton10.EnableLongPress = false;
            siticoneButton10.EnablePressAnimation = true;
            siticoneButton10.EnableRippleEffect = true;
            siticoneButton10.EnableShadow = false;
            siticoneButton10.EnableTextWrapping = false;
            siticoneButton10.Font = new Font("Inter SemiBold", 10.8F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneButton10.GlowColor = Color.FromArgb(100, 255, 255, 255);
            siticoneButton10.GlowIntensity = 100;
            siticoneButton10.GlowRadius = 20F;
            siticoneButton10.GradientBackground = false;
            siticoneButton10.GradientColor = Color.FromArgb(114, 168, 255);
            siticoneButton10.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButton10.HintText = null;
            siticoneButton10.HoverBackColor = Color.FromArgb(114, 168, 255);
            siticoneButton10.HoverFontStyle = FontStyle.Regular;
            siticoneButton10.HoverTextColor = Color.White;
            siticoneButton10.HoverTransitionDuration = 250;
            siticoneButton10.ImageAlign = ContentAlignment.MiddleLeft;
            siticoneButton10.ImagePadding = 5;
            siticoneButton10.ImageSize = new Size(300, 220);
            siticoneButton10.IsRadial = false;
            siticoneButton10.IsReadOnly = false;
            siticoneButton10.IsToggleButton = false;
            siticoneButton10.IsToggled = false;
            siticoneButton10.Location = new Point(1052, 263);
            siticoneButton10.LongPressDurationMS = 1000;
            siticoneButton10.Name = "siticoneButton10";
            siticoneButton10.NormalFontStyle = FontStyle.Regular;
            siticoneButton10.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButton10.ParticleCount = 15;
            siticoneButton10.PressAnimationScale = 0.97F;
            siticoneButton10.PressedBackColor = Color.FromArgb(74, 128, 235);
            siticoneButton10.PressedFontStyle = FontStyle.Regular;
            siticoneButton10.PressTransitionDuration = 150;
            siticoneButton10.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButton10.RippleColor = Color.FromArgb(255, 255, 255);
            siticoneButton10.RippleOpacity = 0.3F;
            siticoneButton10.RippleRadiusMultiplier = 0.6F;
            siticoneButton10.ShadowBlur = 5;
            siticoneButton10.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            siticoneButton10.ShadowOffset = new Point(2, 2);
            siticoneButton10.ShakeDuration = 500;
            siticoneButton10.ShakeIntensity = 5;
            siticoneButton10.Size = new Size(310, 230);
            siticoneButton10.TabIndex = 14;
            siticoneButton10.Text = "Tham gia";
            siticoneButton10.TextAlign = ContentAlignment.MiddleCenter;
            siticoneButton10.TextColor = Color.Black;
            siticoneButton10.TooltipText = null;
            siticoneButton10.UseAdvancedRendering = true;
            siticoneButton10.UseParticles = false;
            // 
            // siticoneButton11
            // 
            siticoneButton11.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButton11.AccessibleName = "Tham gia";
            siticoneButton11.AutoSizeBasedOnText = false;
            siticoneButton11.BackColor = Color.Transparent;
            siticoneButton11.BadgeBackColor = Color.Red;
            siticoneButton11.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            siticoneButton11.BadgeValue = 0;
            siticoneButton11.BadgeValueForeColor = Color.White;
            siticoneButton11.BorderColor = Color.Transparent;
            siticoneButton11.BorderWidth = 2;
            siticoneButton11.ButtonBackColor = Color.FromArgb(117, 164, 127);
            siticoneButton11.ButtonImage = Properties.Resources.background;
            siticoneButton11.CanBeep = true;
            siticoneButton11.CanGlow = false;
            siticoneButton11.CanShake = true;
            siticoneButton11.ContextMenuStripEx = null;
            siticoneButton11.CornerRadiusBottomLeft = 20;
            siticoneButton11.CornerRadiusBottomRight = 20;
            siticoneButton11.CornerRadiusTopLeft = 20;
            siticoneButton11.CornerRadiusTopRight = 20;
            siticoneButton11.CustomCursor = Cursors.Default;
            siticoneButton11.DisabledTextColor = Color.FromArgb(150, 150, 150);
            siticoneButton11.EnableLongPress = false;
            siticoneButton11.EnablePressAnimation = true;
            siticoneButton11.EnableRippleEffect = true;
            siticoneButton11.EnableShadow = false;
            siticoneButton11.EnableTextWrapping = false;
            siticoneButton11.Font = new Font("Inter SemiBold", 10.8F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneButton11.GlowColor = Color.FromArgb(100, 255, 255, 255);
            siticoneButton11.GlowIntensity = 100;
            siticoneButton11.GlowRadius = 20F;
            siticoneButton11.GradientBackground = false;
            siticoneButton11.GradientColor = Color.FromArgb(114, 168, 255);
            siticoneButton11.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButton11.HintText = null;
            siticoneButton11.HoverBackColor = Color.FromArgb(114, 168, 255);
            siticoneButton11.HoverFontStyle = FontStyle.Regular;
            siticoneButton11.HoverTextColor = Color.White;
            siticoneButton11.HoverTransitionDuration = 250;
            siticoneButton11.ImageAlign = ContentAlignment.MiddleLeft;
            siticoneButton11.ImagePadding = 5;
            siticoneButton11.ImageSize = new Size(300, 220);
            siticoneButton11.IsRadial = false;
            siticoneButton11.IsReadOnly = false;
            siticoneButton11.IsToggleButton = false;
            siticoneButton11.IsToggled = false;
            siticoneButton11.Location = new Point(308, 544);
            siticoneButton11.LongPressDurationMS = 1000;
            siticoneButton11.Name = "siticoneButton11";
            siticoneButton11.NormalFontStyle = FontStyle.Regular;
            siticoneButton11.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButton11.ParticleCount = 15;
            siticoneButton11.PressAnimationScale = 0.97F;
            siticoneButton11.PressedBackColor = Color.FromArgb(74, 128, 235);
            siticoneButton11.PressedFontStyle = FontStyle.Regular;
            siticoneButton11.PressTransitionDuration = 150;
            siticoneButton11.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButton11.RippleColor = Color.FromArgb(255, 255, 255);
            siticoneButton11.RippleOpacity = 0.3F;
            siticoneButton11.RippleRadiusMultiplier = 0.6F;
            siticoneButton11.ShadowBlur = 5;
            siticoneButton11.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            siticoneButton11.ShadowOffset = new Point(2, 2);
            siticoneButton11.ShakeDuration = 500;
            siticoneButton11.ShakeIntensity = 5;
            siticoneButton11.Size = new Size(310, 230);
            siticoneButton11.TabIndex = 15;
            siticoneButton11.Text = "Tham gia";
            siticoneButton11.TextAlign = ContentAlignment.MiddleCenter;
            siticoneButton11.TextColor = Color.Black;
            siticoneButton11.TooltipText = null;
            siticoneButton11.UseAdvancedRendering = true;
            siticoneButton11.UseParticles = false;
            // 
            // siticoneButton12
            // 
            siticoneButton12.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButton12.AccessibleName = "Tham gia";
            siticoneButton12.AutoSizeBasedOnText = false;
            siticoneButton12.BackColor = Color.Transparent;
            siticoneButton12.BadgeBackColor = Color.Red;
            siticoneButton12.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            siticoneButton12.BadgeValue = 0;
            siticoneButton12.BadgeValueForeColor = Color.White;
            siticoneButton12.BorderColor = Color.Transparent;
            siticoneButton12.BorderWidth = 2;
            siticoneButton12.ButtonBackColor = Color.FromArgb(117, 164, 127);
            siticoneButton12.ButtonImage = Properties.Resources.background;
            siticoneButton12.CanBeep = true;
            siticoneButton12.CanGlow = false;
            siticoneButton12.CanShake = true;
            siticoneButton12.ContextMenuStripEx = null;
            siticoneButton12.CornerRadiusBottomLeft = 20;
            siticoneButton12.CornerRadiusBottomRight = 20;
            siticoneButton12.CornerRadiusTopLeft = 20;
            siticoneButton12.CornerRadiusTopRight = 20;
            siticoneButton12.CustomCursor = Cursors.Default;
            siticoneButton12.DisabledTextColor = Color.FromArgb(150, 150, 150);
            siticoneButton12.EnableLongPress = false;
            siticoneButton12.EnablePressAnimation = true;
            siticoneButton12.EnableRippleEffect = true;
            siticoneButton12.EnableShadow = false;
            siticoneButton12.EnableTextWrapping = false;
            siticoneButton12.Font = new Font("Inter SemiBold", 10.8F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneButton12.GlowColor = Color.FromArgb(100, 255, 255, 255);
            siticoneButton12.GlowIntensity = 100;
            siticoneButton12.GlowRadius = 20F;
            siticoneButton12.GradientBackground = false;
            siticoneButton12.GradientColor = Color.FromArgb(114, 168, 255);
            siticoneButton12.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButton12.HintText = null;
            siticoneButton12.HoverBackColor = Color.FromArgb(114, 168, 255);
            siticoneButton12.HoverFontStyle = FontStyle.Regular;
            siticoneButton12.HoverTextColor = Color.White;
            siticoneButton12.HoverTransitionDuration = 250;
            siticoneButton12.ImageAlign = ContentAlignment.MiddleLeft;
            siticoneButton12.ImagePadding = 5;
            siticoneButton12.ImageSize = new Size(300, 220);
            siticoneButton12.IsRadial = false;
            siticoneButton12.IsReadOnly = false;
            siticoneButton12.IsToggleButton = false;
            siticoneButton12.IsToggled = false;
            siticoneButton12.Location = new Point(677, 544);
            siticoneButton12.LongPressDurationMS = 1000;
            siticoneButton12.Name = "siticoneButton12";
            siticoneButton12.NormalFontStyle = FontStyle.Regular;
            siticoneButton12.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButton12.ParticleCount = 15;
            siticoneButton12.PressAnimationScale = 0.97F;
            siticoneButton12.PressedBackColor = Color.FromArgb(74, 128, 235);
            siticoneButton12.PressedFontStyle = FontStyle.Regular;
            siticoneButton12.PressTransitionDuration = 150;
            siticoneButton12.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButton12.RippleColor = Color.FromArgb(255, 255, 255);
            siticoneButton12.RippleOpacity = 0.3F;
            siticoneButton12.RippleRadiusMultiplier = 0.6F;
            siticoneButton12.ShadowBlur = 5;
            siticoneButton12.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            siticoneButton12.ShadowOffset = new Point(2, 2);
            siticoneButton12.ShakeDuration = 500;
            siticoneButton12.ShakeIntensity = 5;
            siticoneButton12.Size = new Size(310, 230);
            siticoneButton12.TabIndex = 16;
            siticoneButton12.Text = "Tham gia";
            siticoneButton12.TextAlign = ContentAlignment.MiddleCenter;
            siticoneButton12.TextColor = Color.Black;
            siticoneButton12.TooltipText = null;
            siticoneButton12.UseAdvancedRendering = true;
            siticoneButton12.UseParticles = false;
            // 
            // siticoneButton13
            // 
            siticoneButton13.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButton13.AccessibleName = "Tham gia";
            siticoneButton13.AutoSizeBasedOnText = false;
            siticoneButton13.BackColor = Color.Transparent;
            siticoneButton13.BadgeBackColor = Color.Red;
            siticoneButton13.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            siticoneButton13.BadgeValue = 0;
            siticoneButton13.BadgeValueForeColor = Color.White;
            siticoneButton13.BorderColor = Color.Transparent;
            siticoneButton13.BorderWidth = 2;
            siticoneButton13.ButtonBackColor = Color.FromArgb(117, 164, 127);
            siticoneButton13.ButtonImage = Properties.Resources.background;
            siticoneButton13.CanBeep = true;
            siticoneButton13.CanGlow = false;
            siticoneButton13.CanShake = true;
            siticoneButton13.ContextMenuStripEx = null;
            siticoneButton13.CornerRadiusBottomLeft = 20;
            siticoneButton13.CornerRadiusBottomRight = 20;
            siticoneButton13.CornerRadiusTopLeft = 20;
            siticoneButton13.CornerRadiusTopRight = 20;
            siticoneButton13.CustomCursor = Cursors.Default;
            siticoneButton13.DisabledTextColor = Color.FromArgb(150, 150, 150);
            siticoneButton13.EnableLongPress = false;
            siticoneButton13.EnablePressAnimation = true;
            siticoneButton13.EnableRippleEffect = true;
            siticoneButton13.EnableShadow = false;
            siticoneButton13.EnableTextWrapping = false;
            siticoneButton13.Font = new Font("Inter SemiBold", 10.8F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneButton13.GlowColor = Color.FromArgb(100, 255, 255, 255);
            siticoneButton13.GlowIntensity = 100;
            siticoneButton13.GlowRadius = 20F;
            siticoneButton13.GradientBackground = false;
            siticoneButton13.GradientColor = Color.FromArgb(114, 168, 255);
            siticoneButton13.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButton13.HintText = null;
            siticoneButton13.HoverBackColor = Color.FromArgb(114, 168, 255);
            siticoneButton13.HoverFontStyle = FontStyle.Regular;
            siticoneButton13.HoverTextColor = Color.White;
            siticoneButton13.HoverTransitionDuration = 250;
            siticoneButton13.ImageAlign = ContentAlignment.MiddleLeft;
            siticoneButton13.ImagePadding = 5;
            siticoneButton13.ImageSize = new Size(300, 220);
            siticoneButton13.IsRadial = false;
            siticoneButton13.IsReadOnly = false;
            siticoneButton13.IsToggleButton = false;
            siticoneButton13.IsToggled = false;
            siticoneButton13.Location = new Point(1052, 544);
            siticoneButton13.LongPressDurationMS = 1000;
            siticoneButton13.Name = "siticoneButton13";
            siticoneButton13.NormalFontStyle = FontStyle.Regular;
            siticoneButton13.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButton13.ParticleCount = 15;
            siticoneButton13.PressAnimationScale = 0.97F;
            siticoneButton13.PressedBackColor = Color.FromArgb(74, 128, 235);
            siticoneButton13.PressedFontStyle = FontStyle.Regular;
            siticoneButton13.PressTransitionDuration = 150;
            siticoneButton13.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButton13.RippleColor = Color.FromArgb(255, 255, 255);
            siticoneButton13.RippleOpacity = 0.3F;
            siticoneButton13.RippleRadiusMultiplier = 0.6F;
            siticoneButton13.ShadowBlur = 5;
            siticoneButton13.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            siticoneButton13.ShadowOffset = new Point(2, 2);
            siticoneButton13.ShakeDuration = 500;
            siticoneButton13.ShakeIntensity = 5;
            siticoneButton13.Size = new Size(310, 230);
            siticoneButton13.TabIndex = 17;
            siticoneButton13.Text = "Tham gia";
            siticoneButton13.TextAlign = ContentAlignment.MiddleCenter;
            siticoneButton13.TextColor = Color.Black;
            siticoneButton13.TooltipText = null;
            siticoneButton13.UseAdvancedRendering = true;
            siticoneButton13.UseParticles = false;
            // 
            // sideBar1
            // 
            sideBar1.Location = new Point(0, 0);
            sideBar1.Name = "sideBar1";
            sideBar1.Size = new Size(278, 1250);
            sideBar1.TabIndex = 18;
            // 
            // userProfilePanel2
            // 
            userProfilePanel2.BackColor = Color.Transparent;
            userProfilePanel2.Location = new Point(1111, 13);
            userProfilePanel2.Name = "userProfilePanel2";
            userProfilePanel2.Size = new Size(312, 75);
            userProfilePanel2.TabIndex = 19;
            // 
            // Dashboard
            // 
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(252, 255, 224);
            ClientSize = new Size(1422, 977);
            Controls.Add(userProfilePanel2);
            Controls.Add(sideBar1);
            Controls.Add(siticoneButton13);
            Controls.Add(siticoneButton12);
            Controls.Add(siticoneButton11);
            Controls.Add(siticoneButton10);
            Controls.Add(siticoneButton9);
            Controls.Add(siticoneButton8);
            Controls.Add(siticoneTextBox1);
            Controls.Add(siticoneButton7);
            Controls.Add(sbtn_CreateNewRoom);
            Controls.Add(siticoneLabel2);
            Controls.Add(siticoneLabel1);
            Name = "Dashboard";
            Text = "Dashboard";
            Load += Dashboard_Load;
            ResumeLayout(false);
        }

        #endregion
        private SiticoneNetCoreUI.SiticoneLabel siticoneLabel1;
        private SiticoneNetCoreUI.SiticoneLabel siticoneLabel2;
        private SiticoneNetCoreUI.MySiticoneLicenseSettings mySiticoneLicenseSettings1;
        private SiticoneNetCoreUI.SiticoneButton sbtn_CreateNewRoom;
        private SiticoneNetCoreUI.MySiticoneLicenseSettings mySiticoneLicenseSettings2;
        private SiticoneNetCoreUI.SiticoneButton siticoneButton7;
        private SiticoneNetCoreUI.SiticoneTextBox siticoneTextBox1;
        private SiticoneNetCoreUI.SiticoneButton siticoneButton8;
        private SiticoneNetCoreUI.SiticoneButton siticoneButton9;
        private SiticoneNetCoreUI.SiticoneButton siticoneButton10;
        private SiticoneNetCoreUI.SiticoneButton siticoneButton11;
        private SiticoneNetCoreUI.SiticoneButton siticoneButton12;
        private SiticoneNetCoreUI.SiticoneButton siticoneButton13;
        private UserProfilePanel userProfilePanel1;
        private SiticoneNetCoreUI.MySiticoneLicenseSettings mySiticoneLicenseSettings3;
        private SideBar sideBar1;
        private UserProfilePanel userProfilePanel2;
    }
}