namespace PomoMeetApp.View
{
    partial class Dashboard
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Dashboard));
            siticonePanel1 = new SiticoneNetCoreUI.SiticonePanel();
            siticoneButton2 = new SiticoneNetCoreUI.SiticoneButton();
            siticonePanel6 = new SiticoneNetCoreUI.SiticonePanel();
            siticonePictureBox8 = new SiticoneNetCoreUI.SiticonePictureBox();
            siticonePictureBox7 = new SiticoneNetCoreUI.SiticonePictureBox();
            siticonePictureBox6 = new SiticoneNetCoreUI.SiticonePictureBox();
            siticonePictureBox5 = new SiticoneNetCoreUI.SiticonePictureBox();
            siticonePictureBox3 = new SiticoneNetCoreUI.SiticonePictureBox();
            siticonePictureBox4 = new SiticoneNetCoreUI.SiticonePictureBox();
            siticoneButton5 = new SiticoneNetCoreUI.SiticoneButton();
            siticoneButton4 = new SiticoneNetCoreUI.SiticoneButton();
            siticoneButton3 = new SiticoneNetCoreUI.SiticoneButton();
            siticoneButton1 = new SiticoneNetCoreUI.SiticoneButton();
            siticoneLabel1 = new SiticoneNetCoreUI.SiticoneLabel();
            siticoneLabel2 = new SiticoneNetCoreUI.SiticoneLabel();
            mySiticoneLicenseSettings1 = new SiticoneNetCoreUI.MySiticoneLicenseSettings();
            siticoneButton6 = new SiticoneNetCoreUI.SiticoneButton();
            mySiticoneLicenseSettings2 = new SiticoneNetCoreUI.MySiticoneLicenseSettings();
            siticoneButton7 = new SiticoneNetCoreUI.SiticoneButton();
            siticoneTextBox1 = new SiticoneNetCoreUI.SiticoneTextBox();
            siticoneButton8 = new SiticoneNetCoreUI.SiticoneButton();
            siticoneButton9 = new SiticoneNetCoreUI.SiticoneButton();
            siticoneButton10 = new SiticoneNetCoreUI.SiticoneButton();
            siticoneButton11 = new SiticoneNetCoreUI.SiticoneButton();
            siticoneButton12 = new SiticoneNetCoreUI.SiticoneButton();
            siticoneButton13 = new SiticoneNetCoreUI.SiticoneButton();
            userProfilePanel1 = new UserProfilePanel();
            siticonePanel1.SuspendLayout();
            siticonePanel6.SuspendLayout();
            SuspendLayout();
            // 
            // siticonePanel1
            // 
            siticonePanel1.AcrylicTintColor = Color.FromArgb(128, 255, 255, 255);
            siticonePanel1.BackColor = Color.Transparent;
            siticonePanel1.BorderAlignment = System.Drawing.Drawing2D.PenAlignment.Center;
            siticonePanel1.BorderDashPattern = null;
            siticonePanel1.BorderGradientEndColor = Color.Purple;
            siticonePanel1.BorderGradientStartColor = Color.Blue;
            siticonePanel1.BorderThickness = 2F;
            siticonePanel1.Controls.Add(siticoneButton2);
            siticonePanel1.Controls.Add(siticonePanel6);
            siticonePanel1.Controls.Add(siticonePictureBox7);
            siticonePanel1.Controls.Add(siticonePictureBox6);
            siticonePanel1.Controls.Add(siticonePictureBox5);
            siticonePanel1.Controls.Add(siticonePictureBox3);
            siticonePanel1.Controls.Add(siticonePictureBox4);
            siticonePanel1.Controls.Add(siticoneButton5);
            siticonePanel1.Controls.Add(siticoneButton4);
            siticonePanel1.Controls.Add(siticoneButton3);
            siticonePanel1.Controls.Add(siticoneButton1);
            siticonePanel1.CornerRadiusBottomLeft = 0F;
            siticonePanel1.CornerRadiusBottomRight = 20F;
            siticonePanel1.CornerRadiusTopLeft = 0F;
            siticonePanel1.CornerRadiusTopRight = 20F;
            siticonePanel1.EnableAcrylicEffect = false;
            siticonePanel1.EnableMicaEffect = false;
            siticonePanel1.EnableRippleEffect = false;
            siticonePanel1.FillColor = Color.FromArgb(117, 164, 127);
            siticonePanel1.Font = new Font("Inter", 18F, FontStyle.Regular, GraphicsUnit.Point, 0);
            siticonePanel1.GradientColors = new Color[]
    {
    Color.White,
    Color.LightGray,
    Color.Gray
    };
            siticonePanel1.GradientPositions = new float[]
    {
    0F,
    0.5F,
    1F
    };
            siticonePanel1.Location = new Point(-1, -1);
            siticonePanel1.Name = "siticonePanel1";
            siticonePanel1.PatternStyle = System.Drawing.Drawing2D.HatchStyle.Max;
            siticonePanel1.RippleAlpha = 50;
            siticonePanel1.RippleAlphaDecrement = 3;
            siticonePanel1.RippleColor = Color.FromArgb(50, 255, 255, 255);
            siticonePanel1.RippleMaxSize = 600F;
            siticonePanel1.RippleSpeed = 15F;
            siticonePanel1.ShowBorder = true;
            siticonePanel1.Size = new Size(310, 1050);
            siticonePanel1.TabIndex = 1;
            siticonePanel1.TabStop = true;
            siticonePanel1.UseBorderGradient = false;
            siticonePanel1.UseMultiGradient = false;
            siticonePanel1.UsePatternTexture = false;
            siticonePanel1.UseRadialGradient = false;
            // 
            // siticoneButton2
            // 
            siticoneButton2.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButton2.AccessibleName = "Create";
            siticoneButton2.AutoSizeBasedOnText = false;
            siticoneButton2.BackColor = Color.Transparent;
            siticoneButton2.BadgeBackColor = Color.Red;
            siticoneButton2.BadgeFont = new Font("Segoe UI", 36F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneButton2.BadgeValue = 0;
            siticoneButton2.BadgeValueForeColor = Color.White;
            siticoneButton2.BorderColor = Color.Transparent;
            siticoneButton2.BorderWidth = 2;
            siticoneButton2.ButtonBackColor = Color.Transparent;
            siticoneButton2.ButtonImage = null;
            siticoneButton2.CanBeep = true;
            siticoneButton2.CanGlow = false;
            siticoneButton2.CanShake = true;
            siticoneButton2.ContextMenuStripEx = null;
            siticoneButton2.CornerRadiusBottomLeft = 0;
            siticoneButton2.CornerRadiusBottomRight = 0;
            siticoneButton2.CornerRadiusTopLeft = 0;
            siticoneButton2.CornerRadiusTopRight = 0;
            siticoneButton2.CustomCursor = Cursors.Default;
            siticoneButton2.DisabledTextColor = Color.FromArgb(150, 150, 150);
            siticoneButton2.EnableLongPress = false;
            siticoneButton2.EnablePressAnimation = true;
            siticoneButton2.EnableRippleEffect = true;
            siticoneButton2.EnableShadow = false;
            siticoneButton2.EnableTextWrapping = false;
            siticoneButton2.Font = new Font("Inter", 18F, FontStyle.Regular, GraphicsUnit.Point, 0);
            siticoneButton2.ForeColor = Color.Black;
            siticoneButton2.GlowColor = Color.FromArgb(100, 255, 255, 255);
            siticoneButton2.GlowIntensity = 100;
            siticoneButton2.GlowRadius = 20F;
            siticoneButton2.GradientBackground = false;
            siticoneButton2.GradientColor = Color.FromArgb(114, 168, 255);
            siticoneButton2.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButton2.HintText = null;
            siticoneButton2.HoverBackColor = Color.Transparent;
            siticoneButton2.HoverFontStyle = FontStyle.Regular;
            siticoneButton2.HoverTextColor = Color.White;
            siticoneButton2.HoverTransitionDuration = 250;
            siticoneButton2.ImageAlign = ContentAlignment.MiddleLeft;
            siticoneButton2.ImagePadding = 5;
            siticoneButton2.ImageSize = new Size(16, 16);
            siticoneButton2.IsRadial = false;
            siticoneButton2.IsReadOnly = false;
            siticoneButton2.IsToggleButton = false;
            siticoneButton2.IsToggled = false;
            siticoneButton2.Location = new Point(91, 264);
            siticoneButton2.LongPressDurationMS = 1000;
            siticoneButton2.Name = "siticoneButton2";
            siticoneButton2.NormalFontStyle = FontStyle.Regular;
            siticoneButton2.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButton2.ParticleCount = 15;
            siticoneButton2.PressAnimationScale = 0.97F;
            siticoneButton2.PressedBackColor = Color.White;
            siticoneButton2.PressedFontStyle = FontStyle.Regular;
            siticoneButton2.PressTransitionDuration = 150;
            siticoneButton2.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButton2.RippleColor = Color.FromArgb(255, 255, 255);
            siticoneButton2.RippleOpacity = 0.3F;
            siticoneButton2.RippleRadiusMultiplier = 0.6F;
            siticoneButton2.ShadowBlur = 5;
            siticoneButton2.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            siticoneButton2.ShadowOffset = new Point(2, 2);
            siticoneButton2.ShakeDuration = 500;
            siticoneButton2.ShakeIntensity = 5;
            siticoneButton2.Size = new Size(207, 65);
            siticoneButton2.TabIndex = 13;
            siticoneButton2.Text = "Create";
            siticoneButton2.TextAlign = ContentAlignment.MiddleLeft;
            siticoneButton2.TextColor = Color.FromArgb(252, 255, 224);
            siticoneButton2.TooltipText = null;
            siticoneButton2.UseAdvancedRendering = true;
            siticoneButton2.UseParticles = false;
            // 
            // siticonePanel6
            // 
            siticonePanel6.AcrylicTintColor = Color.FromArgb(128, 255, 255, 255);
            siticonePanel6.BackColor = Color.Transparent;
            siticonePanel6.BorderAlignment = System.Drawing.Drawing2D.PenAlignment.Center;
            siticonePanel6.BorderDashPattern = null;
            siticonePanel6.BorderGradientEndColor = Color.Purple;
            siticonePanel6.BorderGradientStartColor = Color.Blue;
            siticonePanel6.BorderThickness = 2F;
            siticonePanel6.Controls.Add(siticonePictureBox8);
            siticonePanel6.CornerRadiusBottomLeft = 0F;
            siticonePanel6.CornerRadiusBottomRight = 40F;
            siticonePanel6.CornerRadiusTopLeft = 0F;
            siticonePanel6.CornerRadiusTopRight = 40F;
            siticonePanel6.EnableAcrylicEffect = false;
            siticonePanel6.EnableMicaEffect = false;
            siticonePanel6.EnableRippleEffect = false;
            siticonePanel6.FillColor = Color.FromArgb(252, 255, 224);
            siticonePanel6.GradientColors = new Color[]
    {
    Color.White,
    Color.LightGray,
    Color.Gray
    };
            siticonePanel6.GradientPositions = new float[]
    {
    0F,
    0.5F,
    1F
    };
            siticonePanel6.Location = new Point(0, 0);
            siticonePanel6.Name = "siticonePanel6";
            siticonePanel6.PatternStyle = System.Drawing.Drawing2D.HatchStyle.Max;
            siticonePanel6.RippleAlpha = 50;
            siticonePanel6.RippleAlphaDecrement = 3;
            siticonePanel6.RippleColor = Color.FromArgb(50, 255, 255, 255);
            siticonePanel6.RippleMaxSize = 600F;
            siticonePanel6.RippleSpeed = 15F;
            siticonePanel6.ShowBorder = true;
            siticonePanel6.Size = new Size(123, 110);
            siticonePanel6.TabIndex = 12;
            siticonePanel6.TabStop = true;
            siticonePanel6.UseBorderGradient = false;
            siticonePanel6.UseMultiGradient = false;
            siticonePanel6.UsePatternTexture = false;
            siticonePanel6.UseRadialGradient = false;
            // 
            // siticonePictureBox8
            // 
            siticonePictureBox8.BackColor = Color.Transparent;
            siticonePictureBox8.BorderColor = Color.Transparent;
            siticonePictureBox8.BorderWidth = 1;
            siticonePictureBox8.Brightness = 1F;
            siticonePictureBox8.Contrast = 1F;
            siticonePictureBox8.CornerRadius = 0;
            siticonePictureBox8.DraggingSpeed = 3.15F;
            siticonePictureBox8.EnableAsyncLoading = false;
            siticonePictureBox8.EnableCaching = false;
            siticonePictureBox8.EnableDragDrop = false;
            siticonePictureBox8.EnableExtendedImageSources = false;
            siticonePictureBox8.EnableFilters = false;
            siticonePictureBox8.EnableFlipping = false;
            siticonePictureBox8.EnableGlow = false;
            siticonePictureBox8.EnableHighDpiSupport = false;
            siticonePictureBox8.EnableMouseInteraction = false;
            siticonePictureBox8.EnablePlaceholder = false;
            siticonePictureBox8.EnableRotation = false;
            siticonePictureBox8.EnableShadow = false;
            siticonePictureBox8.EnableSlideshow = false;
            siticonePictureBox8.FlipHorizontal = false;
            siticonePictureBox8.FlipVertical = false;
            siticonePictureBox8.Grayscale = false;
            siticonePictureBox8.Image = (Image)resources.GetObject("siticonePictureBox8.Image");
            siticonePictureBox8.ImageOpacity = 1F;
            siticonePictureBox8.Images = (List<Image>)resources.GetObject("siticonePictureBox8.Images");
            siticonePictureBox8.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.HighQualityBicubic;
            siticonePictureBox8.IsCircular = false;
            siticonePictureBox8.Location = new Point(14, 13);
            siticonePictureBox8.MaintainAspectRatio = true;
            siticonePictureBox8.Name = "siticonePictureBox8";
            siticonePictureBox8.PlaceholderImage = null;
            siticonePictureBox8.RotationAngle = 0F;
            siticonePictureBox8.Saturation = 1F;
            siticonePictureBox8.ShowBorder = true;
            siticonePictureBox8.Size = new Size(92, 81);
            siticonePictureBox8.SizeMode = SiticoneNetCoreUI.SiticonePictureBoxSizeMode.Normal;
            siticonePictureBox8.TabIndex = 0;
            siticonePictureBox8.Text = "siticonePictureBox8";
            // 
            // siticonePictureBox7
            // 
            siticonePictureBox7.BackColor = Color.Transparent;
            siticonePictureBox7.BorderColor = Color.Black;
            siticonePictureBox7.BorderWidth = 1;
            siticonePictureBox7.Brightness = 1F;
            siticonePictureBox7.Contrast = 1F;
            siticonePictureBox7.CornerRadius = 0;
            siticonePictureBox7.DraggingSpeed = 3.15F;
            siticonePictureBox7.EnableAsyncLoading = false;
            siticonePictureBox7.EnableCaching = false;
            siticonePictureBox7.EnableDragDrop = false;
            siticonePictureBox7.EnableExtendedImageSources = false;
            siticonePictureBox7.EnableFilters = false;
            siticonePictureBox7.EnableFlipping = false;
            siticonePictureBox7.EnableGlow = false;
            siticonePictureBox7.EnableHighDpiSupport = false;
            siticonePictureBox7.EnableMouseInteraction = false;
            siticonePictureBox7.EnablePlaceholder = false;
            siticonePictureBox7.EnableRotation = false;
            siticonePictureBox7.EnableShadow = false;
            siticonePictureBox7.EnableSlideshow = false;
            siticonePictureBox7.FlipHorizontal = false;
            siticonePictureBox7.FlipVertical = false;
            siticonePictureBox7.Grayscale = false;
            siticonePictureBox7.Image = (Image)resources.GetObject("siticonePictureBox7.Image");
            siticonePictureBox7.ImageOpacity = 1F;
            siticonePictureBox7.Images = (List<Image>)resources.GetObject("siticonePictureBox7.Images");
            siticonePictureBox7.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.HighQualityBicubic;
            siticonePictureBox7.IsCircular = false;
            siticonePictureBox7.Location = new Point(24, 572);
            siticonePictureBox7.MaintainAspectRatio = true;
            siticonePictureBox7.Name = "siticonePictureBox7";
            siticonePictureBox7.PlaceholderImage = null;
            siticonePictureBox7.RotationAngle = 0F;
            siticonePictureBox7.Saturation = 1F;
            siticonePictureBox7.ShowBorder = false;
            siticonePictureBox7.Size = new Size(61, 65);
            siticonePictureBox7.SizeMode = SiticoneNetCoreUI.SiticonePictureBoxSizeMode.Normal;
            siticonePictureBox7.TabIndex = 11;
            siticonePictureBox7.Text = "siticonePictureBox7";
            // 
            // siticonePictureBox6
            // 
            siticonePictureBox6.BackColor = Color.Transparent;
            siticonePictureBox6.BorderColor = Color.Black;
            siticonePictureBox6.BorderWidth = 1;
            siticonePictureBox6.Brightness = 1F;
            siticonePictureBox6.Contrast = 1F;
            siticonePictureBox6.CornerRadius = 0;
            siticonePictureBox6.DraggingSpeed = 3.15F;
            siticonePictureBox6.EnableAsyncLoading = false;
            siticonePictureBox6.EnableCaching = false;
            siticonePictureBox6.EnableDragDrop = false;
            siticonePictureBox6.EnableExtendedImageSources = false;
            siticonePictureBox6.EnableFilters = false;
            siticonePictureBox6.EnableFlipping = false;
            siticonePictureBox6.EnableGlow = false;
            siticonePictureBox6.EnableHighDpiSupport = false;
            siticonePictureBox6.EnableMouseInteraction = false;
            siticonePictureBox6.EnablePlaceholder = false;
            siticonePictureBox6.EnableRotation = false;
            siticonePictureBox6.EnableShadow = false;
            siticonePictureBox6.EnableSlideshow = false;
            siticonePictureBox6.FlipHorizontal = false;
            siticonePictureBox6.FlipVertical = false;
            siticonePictureBox6.Grayscale = false;
            siticonePictureBox6.Image = (Image)resources.GetObject("siticonePictureBox6.Image");
            siticonePictureBox6.ImageOpacity = 1F;
            siticonePictureBox6.Images = (List<Image>)resources.GetObject("siticonePictureBox6.Images");
            siticonePictureBox6.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.HighQualityBicubic;
            siticonePictureBox6.IsCircular = false;
            siticonePictureBox6.Location = new Point(21, 471);
            siticonePictureBox6.MaintainAspectRatio = true;
            siticonePictureBox6.Name = "siticonePictureBox6";
            siticonePictureBox6.PlaceholderImage = null;
            siticonePictureBox6.RotationAngle = 0F;
            siticonePictureBox6.Saturation = 1F;
            siticonePictureBox6.ShowBorder = false;
            siticonePictureBox6.Size = new Size(61, 65);
            siticonePictureBox6.SizeMode = SiticoneNetCoreUI.SiticonePictureBoxSizeMode.Normal;
            siticonePictureBox6.TabIndex = 10;
            siticonePictureBox6.Text = "siticonePictureBox6";
            // 
            // siticonePictureBox5
            // 
            siticonePictureBox5.BackColor = Color.Transparent;
            siticonePictureBox5.BorderColor = Color.Black;
            siticonePictureBox5.BorderWidth = 1;
            siticonePictureBox5.Brightness = 1F;
            siticonePictureBox5.Contrast = 1F;
            siticonePictureBox5.CornerRadius = 0;
            siticonePictureBox5.DraggingSpeed = 3.15F;
            siticonePictureBox5.EnableAsyncLoading = false;
            siticonePictureBox5.EnableCaching = false;
            siticonePictureBox5.EnableDragDrop = false;
            siticonePictureBox5.EnableExtendedImageSources = false;
            siticonePictureBox5.EnableFilters = false;
            siticonePictureBox5.EnableFlipping = false;
            siticonePictureBox5.EnableGlow = false;
            siticonePictureBox5.EnableHighDpiSupport = false;
            siticonePictureBox5.EnableMouseInteraction = false;
            siticonePictureBox5.EnablePlaceholder = false;
            siticonePictureBox5.EnableRotation = false;
            siticonePictureBox5.EnableShadow = false;
            siticonePictureBox5.EnableSlideshow = false;
            siticonePictureBox5.FlipHorizontal = false;
            siticonePictureBox5.FlipVertical = false;
            siticonePictureBox5.Grayscale = false;
            siticonePictureBox5.Image = (Image)resources.GetObject("siticonePictureBox5.Image");
            siticonePictureBox5.ImageOpacity = 1F;
            siticonePictureBox5.Images = (List<Image>)resources.GetObject("siticonePictureBox5.Images");
            siticonePictureBox5.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.HighQualityBicubic;
            siticonePictureBox5.IsCircular = false;
            siticonePictureBox5.Location = new Point(21, 366);
            siticonePictureBox5.MaintainAspectRatio = true;
            siticonePictureBox5.Name = "siticonePictureBox5";
            siticonePictureBox5.PlaceholderImage = null;
            siticonePictureBox5.RotationAngle = 0F;
            siticonePictureBox5.Saturation = 1F;
            siticonePictureBox5.ShowBorder = false;
            siticonePictureBox5.Size = new Size(61, 65);
            siticonePictureBox5.SizeMode = SiticoneNetCoreUI.SiticonePictureBoxSizeMode.Normal;
            siticonePictureBox5.TabIndex = 9;
            siticonePictureBox5.Text = "siticonePictureBox5";
            // 
            // siticonePictureBox3
            // 
            siticonePictureBox3.BackColor = Color.Transparent;
            siticonePictureBox3.BorderColor = Color.Black;
            siticonePictureBox3.BorderWidth = 1;
            siticonePictureBox3.Brightness = 1F;
            siticonePictureBox3.Contrast = 1F;
            siticonePictureBox3.CornerRadius = 0;
            siticonePictureBox3.DraggingSpeed = 3.15F;
            siticonePictureBox3.EnableAsyncLoading = false;
            siticonePictureBox3.EnableCaching = false;
            siticonePictureBox3.EnableDragDrop = false;
            siticonePictureBox3.EnableExtendedImageSources = false;
            siticonePictureBox3.EnableFilters = false;
            siticonePictureBox3.EnableFlipping = false;
            siticonePictureBox3.EnableGlow = false;
            siticonePictureBox3.EnableHighDpiSupport = false;
            siticonePictureBox3.EnableMouseInteraction = false;
            siticonePictureBox3.EnablePlaceholder = false;
            siticonePictureBox3.EnableRotation = false;
            siticonePictureBox3.EnableShadow = false;
            siticonePictureBox3.EnableSlideshow = false;
            siticonePictureBox3.FlipHorizontal = false;
            siticonePictureBox3.FlipVertical = false;
            siticonePictureBox3.Grayscale = false;
            siticonePictureBox3.Image = (Image)resources.GetObject("siticonePictureBox3.Image");
            siticonePictureBox3.ImageOpacity = 1F;
            siticonePictureBox3.Images = (List<Image>)resources.GetObject("siticonePictureBox3.Images");
            siticonePictureBox3.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.HighQualityBicubic;
            siticonePictureBox3.IsCircular = false;
            siticonePictureBox3.Location = new Point(32, 173);
            siticonePictureBox3.MaintainAspectRatio = true;
            siticonePictureBox3.Name = "siticonePictureBox3";
            siticonePictureBox3.PlaceholderImage = null;
            siticonePictureBox3.RotationAngle = 0F;
            siticonePictureBox3.Saturation = 1F;
            siticonePictureBox3.ShowBorder = false;
            siticonePictureBox3.Size = new Size(50, 47);
            siticonePictureBox3.SizeMode = SiticoneNetCoreUI.SiticonePictureBoxSizeMode.Normal;
            siticonePictureBox3.TabIndex = 8;
            siticonePictureBox3.Text = "siticonePictureBox3";
            // 
            // siticonePictureBox4
            // 
            siticonePictureBox4.BackColor = Color.Transparent;
            siticonePictureBox4.BorderColor = Color.Black;
            siticonePictureBox4.BorderWidth = 1;
            siticonePictureBox4.Brightness = 1F;
            siticonePictureBox4.Contrast = 1F;
            siticonePictureBox4.CornerRadius = 0;
            siticonePictureBox4.DraggingSpeed = 3.15F;
            siticonePictureBox4.EnableAsyncLoading = false;
            siticonePictureBox4.EnableCaching = false;
            siticonePictureBox4.EnableDragDrop = false;
            siticonePictureBox4.EnableExtendedImageSources = false;
            siticonePictureBox4.EnableFilters = false;
            siticonePictureBox4.EnableFlipping = false;
            siticonePictureBox4.EnableGlow = false;
            siticonePictureBox4.EnableHighDpiSupport = false;
            siticonePictureBox4.EnableMouseInteraction = false;
            siticonePictureBox4.EnablePlaceholder = false;
            siticonePictureBox4.EnableRotation = false;
            siticonePictureBox4.EnableShadow = false;
            siticonePictureBox4.EnableSlideshow = false;
            siticonePictureBox4.FlipHorizontal = false;
            siticonePictureBox4.FlipVertical = false;
            siticonePictureBox4.Grayscale = false;
            siticonePictureBox4.Image = (Image)resources.GetObject("siticonePictureBox4.Image");
            siticonePictureBox4.ImageOpacity = 1F;
            siticonePictureBox4.Images = (List<Image>)resources.GetObject("siticonePictureBox4.Images");
            siticonePictureBox4.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.HighQualityBicubic;
            siticonePictureBox4.IsCircular = false;
            siticonePictureBox4.Location = new Point(22, 264);
            siticonePictureBox4.MaintainAspectRatio = true;
            siticonePictureBox4.Name = "siticonePictureBox4";
            siticonePictureBox4.PlaceholderImage = null;
            siticonePictureBox4.RotationAngle = 0F;
            siticonePictureBox4.Saturation = 1F;
            siticonePictureBox4.ShowBorder = false;
            siticonePictureBox4.Size = new Size(61, 65);
            siticonePictureBox4.SizeMode = SiticoneNetCoreUI.SiticonePictureBoxSizeMode.Normal;
            siticonePictureBox4.TabIndex = 7;
            siticonePictureBox4.Text = "siticonePictureBox4";
            // 
            // siticoneButton5
            // 
            siticoneButton5.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButton5.AccessibleName = "Đăng Xuất";
            siticoneButton5.AutoSizeBasedOnText = false;
            siticoneButton5.BackColor = Color.Transparent;
            siticoneButton5.BadgeBackColor = Color.Red;
            siticoneButton5.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            siticoneButton5.BadgeValue = 0;
            siticoneButton5.BadgeValueForeColor = Color.White;
            siticoneButton5.BorderColor = Color.Transparent;
            siticoneButton5.BorderWidth = 2;
            siticoneButton5.ButtonBackColor = Color.Transparent;
            siticoneButton5.ButtonImage = null;
            siticoneButton5.CanBeep = true;
            siticoneButton5.CanGlow = false;
            siticoneButton5.CanShake = true;
            siticoneButton5.ContextMenuStripEx = null;
            siticoneButton5.CornerRadiusBottomLeft = 0;
            siticoneButton5.CornerRadiusBottomRight = 0;
            siticoneButton5.CornerRadiusTopLeft = 0;
            siticoneButton5.CornerRadiusTopRight = 0;
            siticoneButton5.CustomCursor = Cursors.Default;
            siticoneButton5.DisabledTextColor = Color.FromArgb(150, 150, 150);
            siticoneButton5.EnableLongPress = false;
            siticoneButton5.EnablePressAnimation = true;
            siticoneButton5.EnableRippleEffect = true;
            siticoneButton5.EnableShadow = false;
            siticoneButton5.EnableTextWrapping = false;
            siticoneButton5.Font = new Font("Inter", 18F, FontStyle.Regular, GraphicsUnit.Point, 0);
            siticoneButton5.ForeColor = Color.Black;
            siticoneButton5.GlowColor = Color.FromArgb(100, 255, 255, 255);
            siticoneButton5.GlowIntensity = 100;
            siticoneButton5.GlowRadius = 20F;
            siticoneButton5.GradientBackground = false;
            siticoneButton5.GradientColor = Color.FromArgb(114, 168, 255);
            siticoneButton5.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButton5.HintText = null;
            siticoneButton5.HoverBackColor = Color.Transparent;
            siticoneButton5.HoverFontStyle = FontStyle.Regular;
            siticoneButton5.HoverTextColor = Color.White;
            siticoneButton5.HoverTransitionDuration = 250;
            siticoneButton5.ImageAlign = ContentAlignment.MiddleLeft;
            siticoneButton5.ImagePadding = 5;
            siticoneButton5.ImageSize = new Size(16, 16);
            siticoneButton5.IsRadial = false;
            siticoneButton5.IsReadOnly = false;
            siticoneButton5.IsToggleButton = false;
            siticoneButton5.IsToggled = false;
            siticoneButton5.Location = new Point(91, 572);
            siticoneButton5.LongPressDurationMS = 1000;
            siticoneButton5.Name = "siticoneButton5";
            siticoneButton5.NormalFontStyle = FontStyle.Regular;
            siticoneButton5.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButton5.ParticleCount = 15;
            siticoneButton5.PressAnimationScale = 0.97F;
            siticoneButton5.PressedBackColor = Color.White;
            siticoneButton5.PressedFontStyle = FontStyle.Regular;
            siticoneButton5.PressTransitionDuration = 150;
            siticoneButton5.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButton5.RippleColor = Color.FromArgb(255, 255, 255);
            siticoneButton5.RippleOpacity = 0.3F;
            siticoneButton5.RippleRadiusMultiplier = 0.6F;
            siticoneButton5.ShadowBlur = 5;
            siticoneButton5.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            siticoneButton5.ShadowOffset = new Point(2, 2);
            siticoneButton5.ShakeDuration = 500;
            siticoneButton5.ShakeIntensity = 5;
            siticoneButton5.Size = new Size(207, 65);
            siticoneButton5.TabIndex = 5;
            siticoneButton5.Text = "Đăng Xuất";
            siticoneButton5.TextAlign = ContentAlignment.MiddleLeft;
            siticoneButton5.TextColor = Color.FromArgb(252, 255, 224);
            siticoneButton5.TooltipText = null;
            siticoneButton5.UseAdvancedRendering = true;
            siticoneButton5.UseParticles = false;
            // 
            // siticoneButton4
            // 
            siticoneButton4.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButton4.AccessibleName = "Cài đặt";
            siticoneButton4.AutoSizeBasedOnText = false;
            siticoneButton4.BackColor = Color.Transparent;
            siticoneButton4.BadgeBackColor = Color.Red;
            siticoneButton4.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            siticoneButton4.BadgeValue = 0;
            siticoneButton4.BadgeValueForeColor = Color.White;
            siticoneButton4.BorderColor = Color.Transparent;
            siticoneButton4.BorderWidth = 2;
            siticoneButton4.ButtonBackColor = Color.Transparent;
            siticoneButton4.ButtonImage = null;
            siticoneButton4.CanBeep = true;
            siticoneButton4.CanGlow = false;
            siticoneButton4.CanShake = true;
            siticoneButton4.ContextMenuStripEx = null;
            siticoneButton4.CornerRadiusBottomLeft = 0;
            siticoneButton4.CornerRadiusBottomRight = 0;
            siticoneButton4.CornerRadiusTopLeft = 0;
            siticoneButton4.CornerRadiusTopRight = 0;
            siticoneButton4.CustomCursor = Cursors.Default;
            siticoneButton4.DisabledTextColor = Color.FromArgb(150, 150, 150);
            siticoneButton4.EnableLongPress = false;
            siticoneButton4.EnablePressAnimation = true;
            siticoneButton4.EnableRippleEffect = true;
            siticoneButton4.EnableShadow = false;
            siticoneButton4.EnableTextWrapping = false;
            siticoneButton4.Font = new Font("Inter", 18F, FontStyle.Regular, GraphicsUnit.Point, 0);
            siticoneButton4.ForeColor = Color.Black;
            siticoneButton4.GlowColor = Color.FromArgb(100, 255, 255, 255);
            siticoneButton4.GlowIntensity = 100;
            siticoneButton4.GlowRadius = 20F;
            siticoneButton4.GradientBackground = false;
            siticoneButton4.GradientColor = Color.FromArgb(114, 168, 255);
            siticoneButton4.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButton4.HintText = null;
            siticoneButton4.HoverBackColor = Color.Transparent;
            siticoneButton4.HoverFontStyle = FontStyle.Regular;
            siticoneButton4.HoverTextColor = Color.White;
            siticoneButton4.HoverTransitionDuration = 250;
            siticoneButton4.ImageAlign = ContentAlignment.MiddleLeft;
            siticoneButton4.ImagePadding = 5;
            siticoneButton4.ImageSize = new Size(16, 16);
            siticoneButton4.IsRadial = false;
            siticoneButton4.IsReadOnly = false;
            siticoneButton4.IsToggleButton = false;
            siticoneButton4.IsToggled = false;
            siticoneButton4.Location = new Point(92, 471);
            siticoneButton4.LongPressDurationMS = 1000;
            siticoneButton4.Name = "siticoneButton4";
            siticoneButton4.NormalFontStyle = FontStyle.Regular;
            siticoneButton4.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButton4.ParticleCount = 15;
            siticoneButton4.PressAnimationScale = 0.97F;
            siticoneButton4.PressedBackColor = Color.White;
            siticoneButton4.PressedFontStyle = FontStyle.Regular;
            siticoneButton4.PressTransitionDuration = 150;
            siticoneButton4.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButton4.RippleColor = Color.FromArgb(255, 255, 255);
            siticoneButton4.RippleOpacity = 0.3F;
            siticoneButton4.RippleRadiusMultiplier = 0.6F;
            siticoneButton4.ShadowBlur = 5;
            siticoneButton4.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            siticoneButton4.ShadowOffset = new Point(2, 2);
            siticoneButton4.ShakeDuration = 500;
            siticoneButton4.ShakeIntensity = 5;
            siticoneButton4.Size = new Size(207, 65);
            siticoneButton4.TabIndex = 4;
            siticoneButton4.Text = "Cài đặt";
            siticoneButton4.TextAlign = ContentAlignment.MiddleLeft;
            siticoneButton4.TextColor = Color.FromArgb(252, 255, 224);
            siticoneButton4.TooltipText = null;
            siticoneButton4.UseAdvancedRendering = true;
            siticoneButton4.UseParticles = false;
            // 
            // siticoneButton3
            // 
            siticoneButton3.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButton3.AccessibleName = "Friends";
            siticoneButton3.AutoSizeBasedOnText = false;
            siticoneButton3.BackColor = Color.Transparent;
            siticoneButton3.BadgeBackColor = Color.Red;
            siticoneButton3.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            siticoneButton3.BadgeValue = 0;
            siticoneButton3.BadgeValueForeColor = Color.White;
            siticoneButton3.BorderColor = Color.Transparent;
            siticoneButton3.BorderWidth = 2;
            siticoneButton3.ButtonBackColor = Color.Transparent;
            siticoneButton3.ButtonImage = null;
            siticoneButton3.CanBeep = true;
            siticoneButton3.CanGlow = false;
            siticoneButton3.CanShake = true;
            siticoneButton3.ContextMenuStripEx = null;
            siticoneButton3.CornerRadiusBottomLeft = 0;
            siticoneButton3.CornerRadiusBottomRight = 0;
            siticoneButton3.CornerRadiusTopLeft = 0;
            siticoneButton3.CornerRadiusTopRight = 0;
            siticoneButton3.CustomCursor = Cursors.Default;
            siticoneButton3.DisabledTextColor = Color.FromArgb(150, 150, 150);
            siticoneButton3.EnableLongPress = false;
            siticoneButton3.EnablePressAnimation = true;
            siticoneButton3.EnableRippleEffect = true;
            siticoneButton3.EnableShadow = false;
            siticoneButton3.EnableTextWrapping = false;
            siticoneButton3.Font = new Font("Inter", 18F, FontStyle.Regular, GraphicsUnit.Point, 0);
            siticoneButton3.ForeColor = Color.Black;
            siticoneButton3.GlowColor = Color.FromArgb(100, 255, 255, 255);
            siticoneButton3.GlowIntensity = 100;
            siticoneButton3.GlowRadius = 20F;
            siticoneButton3.GradientBackground = false;
            siticoneButton3.GradientColor = Color.FromArgb(114, 168, 255);
            siticoneButton3.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButton3.HintText = null;
            siticoneButton3.HoverBackColor = Color.Transparent;
            siticoneButton3.HoverFontStyle = FontStyle.Regular;
            siticoneButton3.HoverTextColor = Color.White;
            siticoneButton3.HoverTransitionDuration = 250;
            siticoneButton3.ImageAlign = ContentAlignment.MiddleLeft;
            siticoneButton3.ImagePadding = 5;
            siticoneButton3.ImageSize = new Size(16, 16);
            siticoneButton3.IsRadial = false;
            siticoneButton3.IsReadOnly = false;
            siticoneButton3.IsToggleButton = false;
            siticoneButton3.IsToggled = false;
            siticoneButton3.Location = new Point(92, 366);
            siticoneButton3.LongPressDurationMS = 1000;
            siticoneButton3.Name = "siticoneButton3";
            siticoneButton3.NormalFontStyle = FontStyle.Regular;
            siticoneButton3.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButton3.ParticleCount = 15;
            siticoneButton3.PressAnimationScale = 0.97F;
            siticoneButton3.PressedBackColor = Color.White;
            siticoneButton3.PressedFontStyle = FontStyle.Regular;
            siticoneButton3.PressTransitionDuration = 150;
            siticoneButton3.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButton3.RippleColor = Color.FromArgb(255, 255, 255);
            siticoneButton3.RippleOpacity = 0.3F;
            siticoneButton3.RippleRadiusMultiplier = 0.6F;
            siticoneButton3.ShadowBlur = 5;
            siticoneButton3.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            siticoneButton3.ShadowOffset = new Point(2, 2);
            siticoneButton3.ShakeDuration = 500;
            siticoneButton3.ShakeIntensity = 5;
            siticoneButton3.Size = new Size(207, 65);
            siticoneButton3.TabIndex = 3;
            siticoneButton3.Text = "Friends";
            siticoneButton3.TextAlign = ContentAlignment.MiddleLeft;
            siticoneButton3.TextColor = Color.FromArgb(252, 255, 224);
            siticoneButton3.TooltipText = null;
            siticoneButton3.UseAdvancedRendering = true;
            siticoneButton3.UseParticles = false;
            // 
            // siticoneButton1
            // 
            siticoneButton1.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButton1.AccessibleName = "Dashboard";
            siticoneButton1.AutoSizeBasedOnText = false;
            siticoneButton1.BackColor = Color.Transparent;
            siticoneButton1.BadgeBackColor = Color.Red;
            siticoneButton1.BadgeFont = new Font("Segoe UI", 36F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneButton1.BadgeValue = 0;
            siticoneButton1.BadgeValueForeColor = Color.White;
            siticoneButton1.BorderColor = Color.Transparent;
            siticoneButton1.BorderWidth = 2;
            siticoneButton1.ButtonBackColor = Color.Transparent;
            siticoneButton1.ButtonImage = null;
            siticoneButton1.CanBeep = true;
            siticoneButton1.CanGlow = false;
            siticoneButton1.CanShake = true;
            siticoneButton1.ContextMenuStripEx = null;
            siticoneButton1.CornerRadiusBottomLeft = 0;
            siticoneButton1.CornerRadiusBottomRight = 0;
            siticoneButton1.CornerRadiusTopLeft = 0;
            siticoneButton1.CornerRadiusTopRight = 0;
            siticoneButton1.CustomCursor = Cursors.Default;
            siticoneButton1.DisabledTextColor = Color.FromArgb(150, 150, 150);
            siticoneButton1.EnableLongPress = false;
            siticoneButton1.EnablePressAnimation = true;
            siticoneButton1.EnableRippleEffect = true;
            siticoneButton1.EnableShadow = false;
            siticoneButton1.EnableTextWrapping = false;
            siticoneButton1.Font = new Font("Inter", 18F, FontStyle.Regular, GraphicsUnit.Point, 0);
            siticoneButton1.ForeColor = Color.Black;
            siticoneButton1.GlowColor = Color.FromArgb(100, 255, 255, 255);
            siticoneButton1.GlowIntensity = 100;
            siticoneButton1.GlowRadius = 20F;
            siticoneButton1.GradientBackground = false;
            siticoneButton1.GradientColor = Color.FromArgb(114, 168, 255);
            siticoneButton1.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButton1.HintText = null;
            siticoneButton1.HoverBackColor = Color.Transparent;
            siticoneButton1.HoverFontStyle = FontStyle.Regular;
            siticoneButton1.HoverTextColor = Color.White;
            siticoneButton1.HoverTransitionDuration = 250;
            siticoneButton1.ImageAlign = ContentAlignment.MiddleLeft;
            siticoneButton1.ImagePadding = 5;
            siticoneButton1.ImageSize = new Size(16, 16);
            siticoneButton1.IsRadial = false;
            siticoneButton1.IsReadOnly = false;
            siticoneButton1.IsToggleButton = false;
            siticoneButton1.IsToggled = false;
            siticoneButton1.Location = new Point(92, 163);
            siticoneButton1.LongPressDurationMS = 1000;
            siticoneButton1.Name = "siticoneButton1";
            siticoneButton1.NormalFontStyle = FontStyle.Regular;
            siticoneButton1.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButton1.ParticleCount = 15;
            siticoneButton1.PressAnimationScale = 0.97F;
            siticoneButton1.PressedBackColor = Color.White;
            siticoneButton1.PressedFontStyle = FontStyle.Regular;
            siticoneButton1.PressTransitionDuration = 150;
            siticoneButton1.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButton1.RippleColor = Color.FromArgb(255, 255, 255);
            siticoneButton1.RippleOpacity = 0.3F;
            siticoneButton1.RippleRadiusMultiplier = 0.6F;
            siticoneButton1.ShadowBlur = 5;
            siticoneButton1.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            siticoneButton1.ShadowOffset = new Point(2, 2);
            siticoneButton1.ShakeDuration = 500;
            siticoneButton1.ShakeIntensity = 5;
            siticoneButton1.Size = new Size(207, 65);
            siticoneButton1.TabIndex = 1;
            siticoneButton1.Text = "Dashboard";
            siticoneButton1.TextAlign = ContentAlignment.MiddleLeft;
            siticoneButton1.TextColor = Color.FromArgb(252, 255, 224);
            siticoneButton1.TooltipText = null;
            siticoneButton1.UseAdvancedRendering = true;
            siticoneButton1.UseParticles = false;
            // 
            // siticoneLabel1
            // 
            siticoneLabel1.BackColor = Color.Transparent;
            siticoneLabel1.Font = new Font("Inter", 24F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneLabel1.Location = new Point(362, 24);
            siticoneLabel1.Name = "siticoneLabel1";
            siticoneLabel1.Size = new Size(141, 68);
            siticoneLabel1.TabIndex = 6;
            siticoneLabel1.Text = "Hi, ";
            // 
            // siticoneLabel2
            // 
            siticoneLabel2.BackColor = Color.Transparent;
            siticoneLabel2.Font = new Font("Inter", 24F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneLabel2.Location = new Point(362, 92);
            siticoneLabel2.Name = "siticoneLabel2";
            siticoneLabel2.Size = new Size(796, 68);
            siticoneLabel2.TabIndex = 7;
            siticoneLabel2.Text = "Chào mừng bạn đến với PomoMeet";
            // 
            // siticoneButton6
            // 
            siticoneButton6.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButton6.AccessibleName = "Create a new room";
            siticoneButton6.AutoSizeBasedOnText = false;
            siticoneButton6.BackColor = Color.Transparent;
            siticoneButton6.BadgeBackColor = Color.Red;
            siticoneButton6.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            siticoneButton6.BadgeValue = 0;
            siticoneButton6.BadgeValueForeColor = Color.White;
            siticoneButton6.BorderColor = Color.Transparent;
            siticoneButton6.BorderWidth = 2;
            siticoneButton6.ButtonBackColor = Color.White;
            siticoneButton6.ButtonImage = Properties.Resources.create_Room1;
            siticoneButton6.CanBeep = true;
            siticoneButton6.CanGlow = false;
            siticoneButton6.CanShake = true;
            siticoneButton6.ContextMenuStripEx = null;
            siticoneButton6.CornerRadiusBottomLeft = 12;
            siticoneButton6.CornerRadiusBottomRight = 12;
            siticoneButton6.CornerRadiusTopLeft = 12;
            siticoneButton6.CornerRadiusTopRight = 12;
            siticoneButton6.CustomCursor = Cursors.Default;
            siticoneButton6.DisabledTextColor = Color.White;
            siticoneButton6.EnableLongPress = false;
            siticoneButton6.EnablePressAnimation = true;
            siticoneButton6.EnableRippleEffect = true;
            siticoneButton6.EnableShadow = false;
            siticoneButton6.EnableTextWrapping = false;
            siticoneButton6.Font = new Font("Inter ExtraBold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneButton6.GlowColor = Color.FromArgb(117, 164, 127);
            siticoneButton6.GlowIntensity = 100;
            siticoneButton6.GlowRadius = 20F;
            siticoneButton6.GradientBackground = true;
            siticoneButton6.GradientColor = Color.FromArgb(117, 164, 127);
            siticoneButton6.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButton6.HintText = null;
            siticoneButton6.HoverBackColor = Color.FromArgb(117, 164, 127);
            siticoneButton6.HoverFontStyle = FontStyle.Regular;
            siticoneButton6.HoverTextColor = Color.White;
            siticoneButton6.HoverTransitionDuration = 250;
            siticoneButton6.ImageAlign = ContentAlignment.MiddleRight;
            siticoneButton6.ImagePadding = 5;
            siticoneButton6.ImageSize = new Size(50, 50);
            siticoneButton6.IsRadial = false;
            siticoneButton6.IsReadOnly = false;
            siticoneButton6.IsToggleButton = false;
            siticoneButton6.IsToggled = false;
            siticoneButton6.Location = new Point(366, 172);
            siticoneButton6.LongPressDurationMS = 1000;
            siticoneButton6.Name = "siticoneButton6";
            siticoneButton6.NormalFontStyle = FontStyle.Regular;
            siticoneButton6.Padding = new Padding(22, 0, 0, 0);
            siticoneButton6.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButton6.ParticleCount = 15;
            siticoneButton6.PressAnimationScale = 0.97F;
            siticoneButton6.PressedBackColor = Color.FromArgb(74, 128, 235);
            siticoneButton6.PressedFontStyle = FontStyle.Regular;
            siticoneButton6.PressTransitionDuration = 150;
            siticoneButton6.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButton6.RippleColor = Color.FromArgb(255, 255, 255);
            siticoneButton6.RippleOpacity = 0.3F;
            siticoneButton6.RippleRadiusMultiplier = 0.6F;
            siticoneButton6.ShadowBlur = 5;
            siticoneButton6.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            siticoneButton6.ShadowOffset = new Point(2, 2);
            siticoneButton6.ShakeDuration = 500;
            siticoneButton6.ShakeIntensity = 5;
            siticoneButton6.Size = new Size(385, 60);
            siticoneButton6.TabIndex = 8;
            siticoneButton6.Text = "Create a new room";
            siticoneButton6.TextAlign = ContentAlignment.MiddleCenter;
            siticoneButton6.TextColor = Color.White;
            siticoneButton6.TooltipText = null;
            siticoneButton6.UseAdvancedRendering = true;
            siticoneButton6.UseParticles = false;
            // 
            // siticoneButton7
            // 
            siticoneButton7.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButton7.AccessibleName = "Join a room";
            siticoneButton7.AutoSizeBasedOnText = false;
            siticoneButton7.BackColor = Color.Transparent;
            siticoneButton7.BadgeBackColor = Color.Red;
            siticoneButton7.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            siticoneButton7.BadgeValue = 0;
            siticoneButton7.BadgeValueForeColor = Color.White;
            siticoneButton7.BorderColor = Color.Transparent;
            siticoneButton7.BorderWidth = 2;
            siticoneButton7.ButtonBackColor = Color.White;
            siticoneButton7.ButtonImage = null;
            siticoneButton7.CanBeep = true;
            siticoneButton7.CanGlow = false;
            siticoneButton7.CanShake = true;
            siticoneButton7.ContextMenuStripEx = null;
            siticoneButton7.CornerRadiusBottomLeft = 12;
            siticoneButton7.CornerRadiusBottomRight = 12;
            siticoneButton7.CornerRadiusTopLeft = 12;
            siticoneButton7.CornerRadiusTopRight = 12;
            siticoneButton7.CustomCursor = Cursors.Default;
            siticoneButton7.DisabledTextColor = Color.White;
            siticoneButton7.EnableLongPress = false;
            siticoneButton7.EnablePressAnimation = true;
            siticoneButton7.EnableRippleEffect = true;
            siticoneButton7.EnableShadow = false;
            siticoneButton7.EnableTextWrapping = false;
            siticoneButton7.Font = new Font("Inter ExtraBold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneButton7.GlowColor = Color.FromArgb(117, 164, 127);
            siticoneButton7.GlowIntensity = 100;
            siticoneButton7.GlowRadius = 20F;
            siticoneButton7.GradientBackground = true;
            siticoneButton7.GradientColor = Color.FromArgb(117, 164, 127);
            siticoneButton7.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButton7.HintText = null;
            siticoneButton7.HoverBackColor = Color.FromArgb(117, 164, 127);
            siticoneButton7.HoverFontStyle = FontStyle.Regular;
            siticoneButton7.HoverTextColor = Color.White;
            siticoneButton7.HoverTransitionDuration = 250;
            siticoneButton7.ImageAlign = ContentAlignment.MiddleRight;
            siticoneButton7.ImagePadding = 5;
            siticoneButton7.ImageSize = new Size(50, 50);
            siticoneButton7.IsRadial = false;
            siticoneButton7.IsReadOnly = false;
            siticoneButton7.IsToggleButton = false;
            siticoneButton7.IsToggled = false;
            siticoneButton7.Location = new Point(774, 172);
            siticoneButton7.LongPressDurationMS = 1000;
            siticoneButton7.Name = "siticoneButton7";
            siticoneButton7.NormalFontStyle = FontStyle.Regular;
            siticoneButton7.Padding = new Padding(22, 0, 0, 0);
            siticoneButton7.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButton7.ParticleCount = 15;
            siticoneButton7.PressAnimationScale = 0.97F;
            siticoneButton7.PressedBackColor = Color.FromArgb(74, 128, 235);
            siticoneButton7.PressedFontStyle = FontStyle.Regular;
            siticoneButton7.PressTransitionDuration = 150;
            siticoneButton7.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButton7.RippleColor = Color.FromArgb(255, 255, 255);
            siticoneButton7.RippleOpacity = 0.3F;
            siticoneButton7.RippleRadiusMultiplier = 0.6F;
            siticoneButton7.ShadowBlur = 5;
            siticoneButton7.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            siticoneButton7.ShadowOffset = new Point(2, 2);
            siticoneButton7.ShakeDuration = 500;
            siticoneButton7.ShakeIntensity = 5;
            siticoneButton7.Size = new Size(202, 60);
            siticoneButton7.TabIndex = 9;
            siticoneButton7.Text = "Join a room";
            siticoneButton7.TextAlign = ContentAlignment.MiddleCenter;
            siticoneButton7.TextColor = Color.White;
            siticoneButton7.TooltipText = null;
            siticoneButton7.UseAdvancedRendering = true;
            siticoneButton7.UseParticles = false;
            // 
            // siticoneTextBox1
            // 
            siticoneTextBox1.AccessibleDescription = "A customizable text input field.";
            siticoneTextBox1.AccessibleName = "Text Box";
            siticoneTextBox1.AccessibleRole = AccessibleRole.Text;
            siticoneTextBox1.BackColor = Color.Transparent;
            siticoneTextBox1.BlinkCount = 3;
            siticoneTextBox1.BlinkShadow = false;
            siticoneTextBox1.BorderColor1 = Color.LightSlateGray;
            siticoneTextBox1.BorderColor2 = Color.LightSlateGray;
            siticoneTextBox1.BorderFocusColor1 = Color.FromArgb(77, 77, 255);
            siticoneTextBox1.BorderFocusColor2 = Color.FromArgb(77, 77, 255);
            siticoneTextBox1.CanShake = true;
            siticoneTextBox1.ContinuousBlink = false;
            siticoneTextBox1.CornerRadiusBottomLeft = 10;
            siticoneTextBox1.CornerRadiusBottomRight = 10;
            siticoneTextBox1.CornerRadiusTopLeft = 10;
            siticoneTextBox1.CornerRadiusTopRight = 10;
            siticoneTextBox1.CursorBlinkRate = 500;
            siticoneTextBox1.CursorColor = Color.Black;
            siticoneTextBox1.CursorHeight = 26;
            siticoneTextBox1.CursorOffset = 0;
            siticoneTextBox1.CursorStyle = SiticoneNetCoreUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            siticoneTextBox1.CursorWidth = 1;
            siticoneTextBox1.DisabledBackColor = Color.WhiteSmoke;
            siticoneTextBox1.DisabledBorderColor = Color.LightGray;
            siticoneTextBox1.DisabledTextColor = Color.Gray;
            siticoneTextBox1.EnableDropShadow = false;
            siticoneTextBox1.FillColor1 = Color.YellowGreen;
            siticoneTextBox1.FillColor2 = Color.White;
            siticoneTextBox1.Font = new Font("Segoe UI", 9.5F);
            siticoneTextBox1.ForeColor = Color.DimGray;
            siticoneTextBox1.HoverBorderColor1 = Color.Gray;
            siticoneTextBox1.HoverBorderColor2 = Color.Gray;
            siticoneTextBox1.IsEnabled = true;
            siticoneTextBox1.Location = new Point(1202, 180);
            siticoneTextBox1.Name = "siticoneTextBox1";
            siticoneTextBox1.PlaceholderColor = Color.Gray;
            siticoneTextBox1.PlaceholderText = "Enter text here...";
            siticoneTextBox1.ReadOnlyBorderColor1 = Color.LightGray;
            siticoneTextBox1.ReadOnlyBorderColor2 = Color.LightGray;
            siticoneTextBox1.ReadOnlyFillColor1 = Color.WhiteSmoke;
            siticoneTextBox1.ReadOnlyFillColor2 = Color.WhiteSmoke;
            siticoneTextBox1.ReadOnlyPlaceholderColor = Color.DarkGray;
            siticoneTextBox1.SelectionBackColor = Color.FromArgb(77, 77, 255);
            siticoneTextBox1.ShadowAnimationDuration = 1;
            siticoneTextBox1.ShadowBlur = 10;
            siticoneTextBox1.ShadowColor = Color.FromArgb(15, 0, 0, 0);
            siticoneTextBox1.Size = new Size(331, 52);
            siticoneTextBox1.SolidBorderColor = Color.LightSlateGray;
            siticoneTextBox1.SolidBorderFocusColor = Color.FromArgb(77, 77, 255);
            siticoneTextBox1.SolidBorderHoverColor = Color.Gray;
            siticoneTextBox1.SolidFillColor = Color.White;
            siticoneTextBox1.TabIndex = 11;
            siticoneTextBox1.Text = "Search here ...";
            siticoneTextBox1.TextPadding = new Padding(16, 0, 6, 0);
            siticoneTextBox1.ValidationErrorMessage = "Invalid input.";
            siticoneTextBox1.ValidationFunction = null;
            // 
            // siticoneButton8
            // 
            siticoneButton8.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButton8.AccessibleName = "Tham gia";
            siticoneButton8.AutoSizeBasedOnText = false;
            siticoneButton8.BackColor = Color.Transparent;
            siticoneButton8.BadgeBackColor = Color.Red;
            siticoneButton8.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            siticoneButton8.BadgeValue = 0;
            siticoneButton8.BadgeValueForeColor = Color.White;
            siticoneButton8.BorderColor = Color.Transparent;
            siticoneButton8.BorderWidth = 2;
            siticoneButton8.ButtonBackColor = Color.FromArgb(117, 164, 127);
            siticoneButton8.ButtonImage = Properties.Resources.background;
            siticoneButton8.CanBeep = true;
            siticoneButton8.CanGlow = false;
            siticoneButton8.CanShake = true;
            siticoneButton8.ContextMenuStripEx = null;
            siticoneButton8.CornerRadiusBottomLeft = 20;
            siticoneButton8.CornerRadiusBottomRight = 20;
            siticoneButton8.CornerRadiusTopLeft = 20;
            siticoneButton8.CornerRadiusTopRight = 20;
            siticoneButton8.CustomCursor = Cursors.Default;
            siticoneButton8.DisabledTextColor = Color.FromArgb(150, 150, 150);
            siticoneButton8.EnableLongPress = false;
            siticoneButton8.EnablePressAnimation = true;
            siticoneButton8.EnableRippleEffect = true;
            siticoneButton8.EnableShadow = false;
            siticoneButton8.EnableTextWrapping = false;
            siticoneButton8.Font = new Font("Inter SemiBold", 10.8F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneButton8.GlowColor = Color.FromArgb(100, 255, 255, 255);
            siticoneButton8.GlowIntensity = 100;
            siticoneButton8.GlowRadius = 20F;
            siticoneButton8.GradientBackground = false;
            siticoneButton8.GradientColor = Color.FromArgb(114, 168, 255);
            siticoneButton8.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButton8.HintText = null;
            siticoneButton8.HoverBackColor = Color.FromArgb(114, 168, 255);
            siticoneButton8.HoverFontStyle = FontStyle.Regular;
            siticoneButton8.HoverTextColor = Color.White;
            siticoneButton8.HoverTransitionDuration = 250;
            siticoneButton8.ImageAlign = ContentAlignment.MiddleLeft;
            siticoneButton8.ImagePadding = 5;
            siticoneButton8.ImageSize = new Size(300, 220);
            siticoneButton8.IsRadial = false;
            siticoneButton8.IsReadOnly = false;
            siticoneButton8.IsToggleButton = false;
            siticoneButton8.IsToggled = false;
            siticoneButton8.Location = new Point(346, 276);
            siticoneButton8.LongPressDurationMS = 1000;
            siticoneButton8.Name = "siticoneButton8";
            siticoneButton8.NormalFontStyle = FontStyle.Regular;
            siticoneButton8.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButton8.ParticleCount = 15;
            siticoneButton8.PressAnimationScale = 0.97F;
            siticoneButton8.PressedBackColor = Color.FromArgb(74, 128, 235);
            siticoneButton8.PressedFontStyle = FontStyle.Regular;
            siticoneButton8.PressTransitionDuration = 150;
            siticoneButton8.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButton8.RippleColor = Color.FromArgb(255, 255, 255);
            siticoneButton8.RippleOpacity = 0.3F;
            siticoneButton8.RippleRadiusMultiplier = 0.6F;
            siticoneButton8.ShadowBlur = 5;
            siticoneButton8.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            siticoneButton8.ShadowOffset = new Point(2, 2);
            siticoneButton8.ShakeDuration = 500;
            siticoneButton8.ShakeIntensity = 5;
            siticoneButton8.Size = new Size(349, 241);
            siticoneButton8.TabIndex = 12;
            siticoneButton8.Text = "Tham gia";
            siticoneButton8.TextAlign = ContentAlignment.MiddleCenter;
            siticoneButton8.TextColor = Color.Black;
            siticoneButton8.TooltipText = null;
            siticoneButton8.UseAdvancedRendering = true;
            siticoneButton8.UseParticles = false;
            // 
            // siticoneButton9
            // 
            siticoneButton9.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButton9.AccessibleName = "Tham gia";
            siticoneButton9.AutoSizeBasedOnText = false;
            siticoneButton9.BackColor = Color.Transparent;
            siticoneButton9.BadgeBackColor = Color.Red;
            siticoneButton9.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            siticoneButton9.BadgeValue = 0;
            siticoneButton9.BadgeValueForeColor = Color.White;
            siticoneButton9.BorderColor = Color.Transparent;
            siticoneButton9.BorderWidth = 2;
            siticoneButton9.ButtonBackColor = Color.FromArgb(117, 164, 127);
            siticoneButton9.ButtonImage = Properties.Resources.background;
            siticoneButton9.CanBeep = true;
            siticoneButton9.CanGlow = false;
            siticoneButton9.CanShake = true;
            siticoneButton9.ContextMenuStripEx = null;
            siticoneButton9.CornerRadiusBottomLeft = 20;
            siticoneButton9.CornerRadiusBottomRight = 20;
            siticoneButton9.CornerRadiusTopLeft = 20;
            siticoneButton9.CornerRadiusTopRight = 20;
            siticoneButton9.CustomCursor = Cursors.Default;
            siticoneButton9.DisabledTextColor = Color.FromArgb(150, 150, 150);
            siticoneButton9.EnableLongPress = false;
            siticoneButton9.EnablePressAnimation = true;
            siticoneButton9.EnableRippleEffect = true;
            siticoneButton9.EnableShadow = false;
            siticoneButton9.EnableTextWrapping = false;
            siticoneButton9.Font = new Font("Inter SemiBold", 10.8F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneButton9.GlowColor = Color.FromArgb(100, 255, 255, 255);
            siticoneButton9.GlowIntensity = 100;
            siticoneButton9.GlowRadius = 20F;
            siticoneButton9.GradientBackground = false;
            siticoneButton9.GradientColor = Color.FromArgb(114, 168, 255);
            siticoneButton9.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButton9.HintText = null;
            siticoneButton9.HoverBackColor = Color.FromArgb(114, 168, 255);
            siticoneButton9.HoverFontStyle = FontStyle.Regular;
            siticoneButton9.HoverTextColor = Color.White;
            siticoneButton9.HoverTransitionDuration = 250;
            siticoneButton9.ImageAlign = ContentAlignment.MiddleLeft;
            siticoneButton9.ImagePadding = 5;
            siticoneButton9.ImageSize = new Size(300, 220);
            siticoneButton9.IsRadial = false;
            siticoneButton9.IsReadOnly = false;
            siticoneButton9.IsToggleButton = false;
            siticoneButton9.IsToggled = false;
            siticoneButton9.Location = new Point(762, 276);
            siticoneButton9.LongPressDurationMS = 1000;
            siticoneButton9.Name = "siticoneButton9";
            siticoneButton9.NormalFontStyle = FontStyle.Regular;
            siticoneButton9.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButton9.ParticleCount = 15;
            siticoneButton9.PressAnimationScale = 0.97F;
            siticoneButton9.PressedBackColor = Color.FromArgb(74, 128, 235);
            siticoneButton9.PressedFontStyle = FontStyle.Regular;
            siticoneButton9.PressTransitionDuration = 150;
            siticoneButton9.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButton9.RippleColor = Color.FromArgb(255, 255, 255);
            siticoneButton9.RippleOpacity = 0.3F;
            siticoneButton9.RippleRadiusMultiplier = 0.6F;
            siticoneButton9.ShadowBlur = 5;
            siticoneButton9.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            siticoneButton9.ShadowOffset = new Point(2, 2);
            siticoneButton9.ShakeDuration = 500;
            siticoneButton9.ShakeIntensity = 5;
            siticoneButton9.Size = new Size(349, 241);
            siticoneButton9.TabIndex = 13;
            siticoneButton9.Text = "Tham gia";
            siticoneButton9.TextAlign = ContentAlignment.MiddleCenter;
            siticoneButton9.TextColor = Color.Black;
            siticoneButton9.TooltipText = null;
            siticoneButton9.UseAdvancedRendering = true;
            siticoneButton9.UseParticles = false;
            // 
            // siticoneButton10
            // 
            siticoneButton10.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButton10.AccessibleName = "Tham gia";
            siticoneButton10.AutoSizeBasedOnText = false;
            siticoneButton10.BackColor = Color.Transparent;
            siticoneButton10.BadgeBackColor = Color.Red;
            siticoneButton10.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            siticoneButton10.BadgeValue = 0;
            siticoneButton10.BadgeValueForeColor = Color.White;
            siticoneButton10.BorderColor = Color.Transparent;
            siticoneButton10.BorderWidth = 2;
            siticoneButton10.ButtonBackColor = Color.FromArgb(117, 164, 127);
            siticoneButton10.ButtonImage = Properties.Resources.background;
            siticoneButton10.CanBeep = true;
            siticoneButton10.CanGlow = false;
            siticoneButton10.CanShake = true;
            siticoneButton10.ContextMenuStripEx = null;
            siticoneButton10.CornerRadiusBottomLeft = 20;
            siticoneButton10.CornerRadiusBottomRight = 20;
            siticoneButton10.CornerRadiusTopLeft = 20;
            siticoneButton10.CornerRadiusTopRight = 20;
            siticoneButton10.CustomCursor = Cursors.Default;
            siticoneButton10.DisabledTextColor = Color.FromArgb(150, 150, 150);
            siticoneButton10.EnableLongPress = false;
            siticoneButton10.EnablePressAnimation = true;
            siticoneButton10.EnableRippleEffect = true;
            siticoneButton10.EnableShadow = false;
            siticoneButton10.EnableTextWrapping = false;
            siticoneButton10.Font = new Font("Inter SemiBold", 10.8F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneButton10.GlowColor = Color.FromArgb(100, 255, 255, 255);
            siticoneButton10.GlowIntensity = 100;
            siticoneButton10.GlowRadius = 20F;
            siticoneButton10.GradientBackground = false;
            siticoneButton10.GradientColor = Color.FromArgb(114, 168, 255);
            siticoneButton10.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButton10.HintText = null;
            siticoneButton10.HoverBackColor = Color.FromArgb(114, 168, 255);
            siticoneButton10.HoverFontStyle = FontStyle.Regular;
            siticoneButton10.HoverTextColor = Color.White;
            siticoneButton10.HoverTransitionDuration = 250;
            siticoneButton10.ImageAlign = ContentAlignment.MiddleLeft;
            siticoneButton10.ImagePadding = 5;
            siticoneButton10.ImageSize = new Size(300, 220);
            siticoneButton10.IsRadial = false;
            siticoneButton10.IsReadOnly = false;
            siticoneButton10.IsToggleButton = false;
            siticoneButton10.IsToggled = false;
            siticoneButton10.Location = new Point(1184, 276);
            siticoneButton10.LongPressDurationMS = 1000;
            siticoneButton10.Name = "siticoneButton10";
            siticoneButton10.NormalFontStyle = FontStyle.Regular;
            siticoneButton10.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButton10.ParticleCount = 15;
            siticoneButton10.PressAnimationScale = 0.97F;
            siticoneButton10.PressedBackColor = Color.FromArgb(74, 128, 235);
            siticoneButton10.PressedFontStyle = FontStyle.Regular;
            siticoneButton10.PressTransitionDuration = 150;
            siticoneButton10.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButton10.RippleColor = Color.FromArgb(255, 255, 255);
            siticoneButton10.RippleOpacity = 0.3F;
            siticoneButton10.RippleRadiusMultiplier = 0.6F;
            siticoneButton10.ShadowBlur = 5;
            siticoneButton10.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            siticoneButton10.ShadowOffset = new Point(2, 2);
            siticoneButton10.ShakeDuration = 500;
            siticoneButton10.ShakeIntensity = 5;
            siticoneButton10.Size = new Size(349, 241);
            siticoneButton10.TabIndex = 14;
            siticoneButton10.Text = "Tham gia";
            siticoneButton10.TextAlign = ContentAlignment.MiddleCenter;
            siticoneButton10.TextColor = Color.Black;
            siticoneButton10.TooltipText = null;
            siticoneButton10.UseAdvancedRendering = true;
            siticoneButton10.UseParticles = false;
            // 
            // siticoneButton11
            // 
            siticoneButton11.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButton11.AccessibleName = "Tham gia";
            siticoneButton11.AutoSizeBasedOnText = false;
            siticoneButton11.BackColor = Color.Transparent;
            siticoneButton11.BadgeBackColor = Color.Red;
            siticoneButton11.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            siticoneButton11.BadgeValue = 0;
            siticoneButton11.BadgeValueForeColor = Color.White;
            siticoneButton11.BorderColor = Color.Transparent;
            siticoneButton11.BorderWidth = 2;
            siticoneButton11.ButtonBackColor = Color.FromArgb(117, 164, 127);
            siticoneButton11.ButtonImage = Properties.Resources.background;
            siticoneButton11.CanBeep = true;
            siticoneButton11.CanGlow = false;
            siticoneButton11.CanShake = true;
            siticoneButton11.ContextMenuStripEx = null;
            siticoneButton11.CornerRadiusBottomLeft = 20;
            siticoneButton11.CornerRadiusBottomRight = 20;
            siticoneButton11.CornerRadiusTopLeft = 20;
            siticoneButton11.CornerRadiusTopRight = 20;
            siticoneButton11.CustomCursor = Cursors.Default;
            siticoneButton11.DisabledTextColor = Color.FromArgb(150, 150, 150);
            siticoneButton11.EnableLongPress = false;
            siticoneButton11.EnablePressAnimation = true;
            siticoneButton11.EnableRippleEffect = true;
            siticoneButton11.EnableShadow = false;
            siticoneButton11.EnableTextWrapping = false;
            siticoneButton11.Font = new Font("Inter SemiBold", 10.8F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneButton11.GlowColor = Color.FromArgb(100, 255, 255, 255);
            siticoneButton11.GlowIntensity = 100;
            siticoneButton11.GlowRadius = 20F;
            siticoneButton11.GradientBackground = false;
            siticoneButton11.GradientColor = Color.FromArgb(114, 168, 255);
            siticoneButton11.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButton11.HintText = null;
            siticoneButton11.HoverBackColor = Color.FromArgb(114, 168, 255);
            siticoneButton11.HoverFontStyle = FontStyle.Regular;
            siticoneButton11.HoverTextColor = Color.White;
            siticoneButton11.HoverTransitionDuration = 250;
            siticoneButton11.ImageAlign = ContentAlignment.MiddleLeft;
            siticoneButton11.ImagePadding = 5;
            siticoneButton11.ImageSize = new Size(300, 220);
            siticoneButton11.IsRadial = false;
            siticoneButton11.IsReadOnly = false;
            siticoneButton11.IsToggleButton = false;
            siticoneButton11.IsToggled = false;
            siticoneButton11.Location = new Point(346, 571);
            siticoneButton11.LongPressDurationMS = 1000;
            siticoneButton11.Name = "siticoneButton11";
            siticoneButton11.NormalFontStyle = FontStyle.Regular;
            siticoneButton11.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButton11.ParticleCount = 15;
            siticoneButton11.PressAnimationScale = 0.97F;
            siticoneButton11.PressedBackColor = Color.FromArgb(74, 128, 235);
            siticoneButton11.PressedFontStyle = FontStyle.Regular;
            siticoneButton11.PressTransitionDuration = 150;
            siticoneButton11.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButton11.RippleColor = Color.FromArgb(255, 255, 255);
            siticoneButton11.RippleOpacity = 0.3F;
            siticoneButton11.RippleRadiusMultiplier = 0.6F;
            siticoneButton11.ShadowBlur = 5;
            siticoneButton11.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            siticoneButton11.ShadowOffset = new Point(2, 2);
            siticoneButton11.ShakeDuration = 500;
            siticoneButton11.ShakeIntensity = 5;
            siticoneButton11.Size = new Size(349, 241);
            siticoneButton11.TabIndex = 15;
            siticoneButton11.Text = "Tham gia";
            siticoneButton11.TextAlign = ContentAlignment.MiddleCenter;
            siticoneButton11.TextColor = Color.Black;
            siticoneButton11.TooltipText = null;
            siticoneButton11.UseAdvancedRendering = true;
            siticoneButton11.UseParticles = false;
            // 
            // siticoneButton12
            // 
            siticoneButton12.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButton12.AccessibleName = "Tham gia";
            siticoneButton12.AutoSizeBasedOnText = false;
            siticoneButton12.BackColor = Color.Transparent;
            siticoneButton12.BadgeBackColor = Color.Red;
            siticoneButton12.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            siticoneButton12.BadgeValue = 0;
            siticoneButton12.BadgeValueForeColor = Color.White;
            siticoneButton12.BorderColor = Color.Transparent;
            siticoneButton12.BorderWidth = 2;
            siticoneButton12.ButtonBackColor = Color.FromArgb(117, 164, 127);
            siticoneButton12.ButtonImage = Properties.Resources.background;
            siticoneButton12.CanBeep = true;
            siticoneButton12.CanGlow = false;
            siticoneButton12.CanShake = true;
            siticoneButton12.ContextMenuStripEx = null;
            siticoneButton12.CornerRadiusBottomLeft = 20;
            siticoneButton12.CornerRadiusBottomRight = 20;
            siticoneButton12.CornerRadiusTopLeft = 20;
            siticoneButton12.CornerRadiusTopRight = 20;
            siticoneButton12.CustomCursor = Cursors.Default;
            siticoneButton12.DisabledTextColor = Color.FromArgb(150, 150, 150);
            siticoneButton12.EnableLongPress = false;
            siticoneButton12.EnablePressAnimation = true;
            siticoneButton12.EnableRippleEffect = true;
            siticoneButton12.EnableShadow = false;
            siticoneButton12.EnableTextWrapping = false;
            siticoneButton12.Font = new Font("Inter SemiBold", 10.8F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneButton12.GlowColor = Color.FromArgb(100, 255, 255, 255);
            siticoneButton12.GlowIntensity = 100;
            siticoneButton12.GlowRadius = 20F;
            siticoneButton12.GradientBackground = false;
            siticoneButton12.GradientColor = Color.FromArgb(114, 168, 255);
            siticoneButton12.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButton12.HintText = null;
            siticoneButton12.HoverBackColor = Color.FromArgb(114, 168, 255);
            siticoneButton12.HoverFontStyle = FontStyle.Regular;
            siticoneButton12.HoverTextColor = Color.White;
            siticoneButton12.HoverTransitionDuration = 250;
            siticoneButton12.ImageAlign = ContentAlignment.MiddleLeft;
            siticoneButton12.ImagePadding = 5;
            siticoneButton12.ImageSize = new Size(300, 220);
            siticoneButton12.IsRadial = false;
            siticoneButton12.IsReadOnly = false;
            siticoneButton12.IsToggleButton = false;
            siticoneButton12.IsToggled = false;
            siticoneButton12.Location = new Point(762, 571);
            siticoneButton12.LongPressDurationMS = 1000;
            siticoneButton12.Name = "siticoneButton12";
            siticoneButton12.NormalFontStyle = FontStyle.Regular;
            siticoneButton12.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButton12.ParticleCount = 15;
            siticoneButton12.PressAnimationScale = 0.97F;
            siticoneButton12.PressedBackColor = Color.FromArgb(74, 128, 235);
            siticoneButton12.PressedFontStyle = FontStyle.Regular;
            siticoneButton12.PressTransitionDuration = 150;
            siticoneButton12.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButton12.RippleColor = Color.FromArgb(255, 255, 255);
            siticoneButton12.RippleOpacity = 0.3F;
            siticoneButton12.RippleRadiusMultiplier = 0.6F;
            siticoneButton12.ShadowBlur = 5;
            siticoneButton12.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            siticoneButton12.ShadowOffset = new Point(2, 2);
            siticoneButton12.ShakeDuration = 500;
            siticoneButton12.ShakeIntensity = 5;
            siticoneButton12.Size = new Size(349, 241);
            siticoneButton12.TabIndex = 16;
            siticoneButton12.Text = "Tham gia";
            siticoneButton12.TextAlign = ContentAlignment.MiddleCenter;
            siticoneButton12.TextColor = Color.Black;
            siticoneButton12.TooltipText = null;
            siticoneButton12.UseAdvancedRendering = true;
            siticoneButton12.UseParticles = false;
            // 
            // siticoneButton13
            // 
            siticoneButton13.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButton13.AccessibleName = "Tham gia";
            siticoneButton13.AutoSizeBasedOnText = false;
            siticoneButton13.BackColor = Color.Transparent;
            siticoneButton13.BadgeBackColor = Color.Red;
            siticoneButton13.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            siticoneButton13.BadgeValue = 0;
            siticoneButton13.BadgeValueForeColor = Color.White;
            siticoneButton13.BorderColor = Color.Transparent;
            siticoneButton13.BorderWidth = 2;
            siticoneButton13.ButtonBackColor = Color.FromArgb(117, 164, 127);
            siticoneButton13.ButtonImage = Properties.Resources.background;
            siticoneButton13.CanBeep = true;
            siticoneButton13.CanGlow = false;
            siticoneButton13.CanShake = true;
            siticoneButton13.ContextMenuStripEx = null;
            siticoneButton13.CornerRadiusBottomLeft = 20;
            siticoneButton13.CornerRadiusBottomRight = 20;
            siticoneButton13.CornerRadiusTopLeft = 20;
            siticoneButton13.CornerRadiusTopRight = 20;
            siticoneButton13.CustomCursor = Cursors.Default;
            siticoneButton13.DisabledTextColor = Color.FromArgb(150, 150, 150);
            siticoneButton13.EnableLongPress = false;
            siticoneButton13.EnablePressAnimation = true;
            siticoneButton13.EnableRippleEffect = true;
            siticoneButton13.EnableShadow = false;
            siticoneButton13.EnableTextWrapping = false;
            siticoneButton13.Font = new Font("Inter SemiBold", 10.8F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneButton13.GlowColor = Color.FromArgb(100, 255, 255, 255);
            siticoneButton13.GlowIntensity = 100;
            siticoneButton13.GlowRadius = 20F;
            siticoneButton13.GradientBackground = false;
            siticoneButton13.GradientColor = Color.FromArgb(114, 168, 255);
            siticoneButton13.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButton13.HintText = null;
            siticoneButton13.HoverBackColor = Color.FromArgb(114, 168, 255);
            siticoneButton13.HoverFontStyle = FontStyle.Regular;
            siticoneButton13.HoverTextColor = Color.White;
            siticoneButton13.HoverTransitionDuration = 250;
            siticoneButton13.ImageAlign = ContentAlignment.MiddleLeft;
            siticoneButton13.ImagePadding = 5;
            siticoneButton13.ImageSize = new Size(300, 220);
            siticoneButton13.IsRadial = false;
            siticoneButton13.IsReadOnly = false;
            siticoneButton13.IsToggleButton = false;
            siticoneButton13.IsToggled = false;
            siticoneButton13.Location = new Point(1184, 571);
            siticoneButton13.LongPressDurationMS = 1000;
            siticoneButton13.Name = "siticoneButton13";
            siticoneButton13.NormalFontStyle = FontStyle.Regular;
            siticoneButton13.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButton13.ParticleCount = 15;
            siticoneButton13.PressAnimationScale = 0.97F;
            siticoneButton13.PressedBackColor = Color.FromArgb(74, 128, 235);
            siticoneButton13.PressedFontStyle = FontStyle.Regular;
            siticoneButton13.PressTransitionDuration = 150;
            siticoneButton13.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButton13.RippleColor = Color.FromArgb(255, 255, 255);
            siticoneButton13.RippleOpacity = 0.3F;
            siticoneButton13.RippleRadiusMultiplier = 0.6F;
            siticoneButton13.ShadowBlur = 5;
            siticoneButton13.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            siticoneButton13.ShadowOffset = new Point(2, 2);
            siticoneButton13.ShakeDuration = 500;
            siticoneButton13.ShakeIntensity = 5;
            siticoneButton13.Size = new Size(349, 241);
            siticoneButton13.TabIndex = 17;
            siticoneButton13.Text = "Tham gia";
            siticoneButton13.TextAlign = ContentAlignment.MiddleCenter;
            siticoneButton13.TextColor = Color.Black;
            siticoneButton13.TooltipText = null;
            siticoneButton13.UseAdvancedRendering = true;
            siticoneButton13.UseParticles = false;
            // 
            // userProfilePanel1
            // 
            userProfilePanel1.BackColor = Color.Transparent;
            userProfilePanel1.Location = new Point(1290, 12);
            userProfilePanel1.Name = "userProfilePanel1";
            userProfilePanel1.Size = new Size(312, 75);
            userProfilePanel1.TabIndex = 18;
            // 
            // Dashboard
            // 
            AutoScaleDimensions = new SizeF(9F, 21F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1600, 1026);
            Controls.Add(userProfilePanel1);
            Controls.Add(siticoneButton13);
            Controls.Add(siticoneButton12);
            Controls.Add(siticoneButton11);
            Controls.Add(siticoneButton10);
            Controls.Add(siticoneButton9);
            Controls.Add(siticoneButton8);
            Controls.Add(siticoneTextBox1);
            Controls.Add(siticoneButton7);
            Controls.Add(siticoneButton6);
            Controls.Add(siticoneLabel2);
            Controls.Add(siticoneLabel1);
            Controls.Add(siticonePanel1);
            Name = "Dashboard";
            Text = "Dashboard";
            Load += Dashboard_Load;
            siticonePanel1.ResumeLayout(false);
            siticonePanel6.ResumeLayout(false);
            ResumeLayout(false);
        }

        #endregion

        private SiticoneNetCoreUI.SiticonePanel siticonePanel1;
        private SiticoneNetCoreUI.SiticoneButton siticoneButton2;
        private SiticoneNetCoreUI.SiticonePanel siticonePanel6;
        private SiticoneNetCoreUI.SiticonePictureBox siticonePictureBox8;
        private SiticoneNetCoreUI.SiticonePictureBox siticonePictureBox7;
        private SiticoneNetCoreUI.SiticonePictureBox siticonePictureBox6;
        private SiticoneNetCoreUI.SiticonePictureBox siticonePictureBox5;
        private SiticoneNetCoreUI.SiticonePictureBox siticonePictureBox3;
        private SiticoneNetCoreUI.SiticonePictureBox siticonePictureBox4;
        private SiticoneNetCoreUI.SiticoneButton siticoneButton5;
        private SiticoneNetCoreUI.SiticoneButton siticoneButton4;
        private SiticoneNetCoreUI.SiticoneButton siticoneButton3;
        private SiticoneNetCoreUI.SiticoneButton siticoneButton1;
        private SiticoneNetCoreUI.SiticoneLabel siticoneLabel1;
        private SiticoneNetCoreUI.SiticoneLabel siticoneLabel2;
        private SiticoneNetCoreUI.MySiticoneLicenseSettings mySiticoneLicenseSettings1;
        private SiticoneNetCoreUI.SiticoneButton siticoneButton6;
        private SiticoneNetCoreUI.MySiticoneLicenseSettings mySiticoneLicenseSettings2;
        private SiticoneNetCoreUI.SiticoneButton siticoneButton7;
        private SiticoneNetCoreUI.SiticoneTextBox siticoneTextBox1;
        private SiticoneNetCoreUI.SiticoneButton siticoneButton8;
        private SiticoneNetCoreUI.SiticoneButton siticoneButton9;
        private SiticoneNetCoreUI.SiticoneButton siticoneButton10;
        private SiticoneNetCoreUI.SiticoneButton siticoneButton11;
        private SiticoneNetCoreUI.SiticoneButton siticoneButton12;
        private SiticoneNetCoreUI.SiticoneButton siticoneButton13;
        private UserProfilePanel userProfilePanel1;
    }
}